### PR TITLE
[#6639] Refactored client_api_allowlist interface (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Running core tests.

### CODE REVIEW

**Comment by korydraughn** [comment]
All core tests and unit tests passed (Ubuntu 20 / Postgres).

**Review by alanking — COMMENTED** [review]
If you could add some more words to the actual commit message about what changed, I think that would be helpful. Otherwise, this looks good to go

**Comment by korydraughn** [comment]
Updated the commit msg. Please review.

**Review by alanking — APPROVED** [review]
Wonderful

**Comment by korydraughn** [comment]
Added #

**Pull request merged**
