### PR TITLE
Oracle support and Large IDs (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
- Verified that the atomic ACLs/Metadata API plugins work against Oracle.
- Verified that the data object finalize API plugin (using nanodbc) works against Oracle.

This needs to be run through CI.

### CODE REVIEW

**Comment by trel** [comment]
great - do we need a couple issue numbers for this work?   what does the question mark on the isolation level commit represent?

**Comment by korydraughn** [comment]
That question mark will be removed in the final PR.

**Comment by trel** [comment]
issue numbers looks good - please # when ready.

**Comment by korydraughn** [comment]
added #'s

**Pull request merged**
