### PR TITLE
[#6492] Added github workflow for clang-tidy (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
Seems good to me.

Let's leave the issue open until we see it in use a couple times.

**Comment by korydraughn** [comment]
I think we can go ahead and merge this. This gives us a baseline to work with.

We can tweak the config as we gain more experience.

**Comment by trel** [comment]
agreed

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
