### PR TITLE
[4421] Added detached mode for unixfilesystem resource (4-3-stable)

### PR DESCRIPTION
**Pull request by JustinKyleJames**
All unixfilesystem tests were run and passed.

### CODE REVIEW

**Comment by trel** [comment]
one conflict now

**Comment by JustinKyleJames** [comment]
> one conflict now

This was the one I referred to earlier.  The previous change must have been merged in the meantime.  Will resolve.

**Comment by alanking** [comment]
For reference...

cherry-picked from https://github.com/irods/irods/pull/6525

**Comment by JustinKyleJames** [comment]
> one conflict now

Resolved it and pushed.

**Review by alanking — APPROVED** [review]
Identical to main, so seems good to me

**Review by korydraughn — APPROVED** [review]
I just realized that the `is_host_in_host_list` function takes a `const std::string_view&`. We need to remove the ampersand from that parameter.

Let's get this in as-is so that main and 4-3-stable line up. And then let's handle the removal of the ampersand in a separate PR.

**Comment by alanking** [comment]
Are we ready for #'s on this?

**Comment by JustinKyleJames** [comment]
> I just realized that the `is_host_in_host_list` function takes a `const std::string_view&`. We need to remove the ampersand from that parameter.
> 
> Let's get this in as-is so that main and 4-3-stable line up. And then let's handle the removal of the ampersand in a separate PR.

Yes, there is an issue on that.  I can fix and open another PR for main and 4-3-stable ASAP.

**Comment by JustinKyleJames** [comment]
Added pound.

**Pull request merged**
