### PR TITLE
[6169] updates for metaclass, test generation (main)

### PR DESCRIPTION
**Pull request by d-w-moore**
#6206 for explanation

### CODE REVIEW

**Review by alanking — DISMISSED** [review]

**Comment by trel** [comment]
gotta squash em

**Comment by trel** [comment]
in the commit message...   "entirely it in" -> "entirely in"

**Comment by d-w-moore** [comment]
done, #'d

**Comment by trel** [comment]
entirey -> entirely

**Comment by d-w-moore** [comment]
> entirey -> entirely

(－‸ლ)

**Pull request merged**
