### PR TITLE
4 2 stable Increase max password length for openid tokens

### PR DESCRIPTION
**Pull request by emedernach**
In order to use openid tokens for authentication we needed to increase the maximum password length.

modified:   lib/api/include/authenticate.h
modified:   plugins/database/src/db_plugin.cpp

Here is the diff:

```diff
diff --git a/lib/api/include/authenticate.h b/lib/api/include/authenticate.h
index 1d15d93..6af133e 100644
--- a/lib/api/include/authenticate.h
+++ b/lib/api/include/authenticate.h
@@ -6,7 +6,8 @@
 #define AUTH_SUBOP_REQ_AUTH "request challenge"
 #define AUTH_SUBOP_RESP "challenge response"
 
-#define MAX_PASSWORD_LEN 50
+// Increased password max size for OpenID token 
+#define MAX_PASSWORD_LEN 65536
 #define CHALLENGE_LEN 64    // 64 bytes of data and terminating null
 #define RESPONSE_LEN 16     // 16 bytes of data and terminating null
 
diff --git a/plugins/database/src/db_plugin.cpp b/plugins/database/src/db_plugin.cpp
index 3bbd2e3..c1fb300 100644
--- a/plugins/database/src/db_plugin.cpp
+++ b/plugins/database/src/db_plugin.cpp
@@ -344,7 +344,7 @@ irods::error determine_user_has_modify_metadata_access(
         std::vector<std::string> bind_vars;
         int status = cmlGetIntegerValueFromSql(
                          "select token_id  from R_TOKN_MAIN where token_name = 'modify metadata' and token_namespace = 'access_type'",
-			 &access_needed,
+                         &access_needed,
                          bind_vars,
                          &icss );
         if( status < 0 ) {
@@ -369,8 +369,8 @@ irods::error determine_user_has_modify_metadata_access(
         bind_vars.push_back( _user_name.c_str() );
         bind_vars.push_back( _zone.c_str() );
         status = cmlGetIntegerValueFromSql(
-	             query.c_str(),
-	             &access_permission,
+                     query.c_str(),
+                     &access_permission,
                      bind_vars,
                      &icss );
         if ( status == CAT_NO_ROWS_FOUND ) {
@@ -402,8 +402,8 @@ irods::error determine_user_has_modify_metadata_access(
         bind_vars.push_back( _user_name.c_str() );
         bind_vars.push_back( _zone.c_str() );
         status = cmlGetIntegerValueFromSql(
-	             query.c_str(),
-	             &access_permission_count,
+                     query.c_str(),
+                     &access_permission_count,
                      bind_vars,
                      &icss );
         if( 0 != status ) {
@@ -3770,11 +3770,11 @@ irods::error db_add_child_resc_op(
               child_parent_name);
 
     if(!ret.ok()) {
-	if( SYS_RESC_DOES_NOT_EXIST == ret.code() ) {
-	    return ERROR(
+        if( SYS_RESC_DOES_NOT_EXIST == ret.code() ) {
+            return ERROR(
                        CHILD_NOT_FOUND,
                        child_parent_name.c_str());
-	}
+        }
         return PASS(ret);
     }
 
@@ -7372,8 +7372,8 @@ irods::error db_update_pam_password_op(
     char myTime[50];
     char rBuf[200];
     size_t i, j;
-    char randomPw[50];
-    char randomPwEncoded[50];
+    char randomPw[MAX_PASSWORD_LEN]; 
+    char randomPwEncoded[MAX_PASSWORD_LEN];
     int status;
     char passwordInIcat[MAX_PASSWORD_LEN + 2];
     char passwordModifyTime[50];
@@ -7495,7 +7495,7 @@ irods::error db_update_pam_password_op(
     while ( !pw_good ) {
         j = 0;
         get64RandomBytes( rBuf );
-        for ( i = 0; i < 50 && j < irods_pam_password_len - 1; i++ ) {
+        for ( i = 0; i < MAX_PASSWORD_LEN && j < irods_pam_password_len - 1; i++ ) {
             char c;
             c = rBuf[i] & 0x7f;
             if ( c < '0' ) {
@@ -7507,16 +7507,13 @@ irods::error db_update_pam_password_op(
             }
         }
         randomPw[j] = '\0';
-
         snprintf( randomPwEncoded, sizeof( randomPwEncoded ), "%s", randomPw );
         icatScramble( randomPwEncoded );
         if ( !strstr( randomPwEncoded, "\'" ) ) {
             pw_good = true;
-
         }
         else {
             rodsLog( LOG_DEBUG, "chlUpdateIrodsPamPassword :: getting a new password [%s] has a single quote", randomPwEncoded );
-
         }
 
     } // while

```

### CODE REVIEW

**Comment by trel** [comment]
This PR is currently trying to merge against the master branch - please retarget this pull request against 4-2-stable.

**Comment by emedernach** [comment]
Hello, sorry I cannot push my local tag as I don't have the permission right to write. What should I do ?

**Comment by trel** [comment]
You can make a new pull request from your 4-2-stable branch to the irods/irods 4-2-stable branch.    This one was created against the irods/irods master branch.

Once you do that, we can just close this one.

**Comment by emedernach** [comment]
Thanks I forked and created a branch to merge with a new pull request.

**Pull request closed without merging**
