### PR TITLE
[8017] Modify schema file to enforce required attributes (main)

### PR DESCRIPTION
**Pull request by FifthPotato**
Not sure if anything else is required for this.

### CODE REVIEW

**Comment by korydraughn** [comment]
See if you can capture this in a test. We want to avoid going backwards as much as possible.

I think IrodsController and IrodsConfig are probably what you want.

**Comment by FifthPotato** [comment]
> See if you can capture this in a test. We want to avoid going backwards as much as possible.
> 
> I think IrodsController and IrodsConfig are probably what you want.

I think we've now agreed not to do a test for this. In that case, is there anything else necessary for this?

**Review by alanking — APPROVED** [review]
Possibly include some language in the commit message about *which* required attributes are being enforced? I'm not so hung up on that. Up to you.

**Comment by alanking** [comment]
@FifthPotato - Also, please cherry-pick to 4-3-stable. Thanks

**Pull request merged**
