### PR TITLE
[#2759] Delay server now honors a rule's priority (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Valid priority levels are defined by the following range: [1 - 9]

The delay server gathers and schedules rules in descending order of
priority level.

`<PRI>` tag is no longer supported by the delay(). Use `<PRIORITY>` instead.
Attempting to use `<PRI>` will result in an error.

Reoccurring rules that have an empty priority level will be updated to have a
priority level of 5 following successful execution. This also applies to
rules that have an invalid priority level.

### CODE REVIEW

**Comment by korydraughn** [comment]
`iqmod` can set the priority to invalid values. The API that allows this needs to be updated to enforce valid priority values.

**Comment by korydraughn** [comment]
How do we want to handle the `<PRI>` tag?
- Do we return an error when it is provided?
- Do we accept it and log a message about it being deprecated and up for removal in 4.3?
- Do we do something else?

**Comment by trel** [comment]
Since there are zero known usages for it today, I think we're okay treating `PRI` as an error and providing a good error message.

**Comment by trel** [comment]
nope - seems good.

**Comment by korydraughn** [comment]
Added tests.

The tests don't check the log file for messages because their appearance is unreliable. However, I have verified at the bench that appropriate messages appear in the log file.

Running this PR through CI.

**Comment by korydraughn** [comment]
passed CI

added #

**Pull request merged**
