### PR TITLE
See issue #6974

### PR DESCRIPTION
**Pull request by ll4strw**

### CODE REVIEW

**Comment by trel** [comment]
do we need to set a default value?

we do that for most/all of the other cmake variables that we introduce/use.

**Comment by korydraughn** [comment]
I thought all of those options for externals packages can be overwritten.

The option used to be something like `-DIRODS_EXTERNALS_FULLPATH_CLANG=/path/to/your/clang/compiler` or `-DIRODS_EXTERNALS_FULLPATH_FMT=/path/to/your/fmt`.

@ll4strw Have you tried using these variables to change which libraries are used?

I think we only need to adjust the `LD_LIBRARY_PATH` line?

@SwooshyCueb Any thoughts on this PR?

**Comment by korydraughn** [comment]
> My bad. I was mistaken. Overwriting the variables -DIRODS_EXTERNALS_FULLPATH_* works fine.

Excellent.

> Changing only LD_LIBRARY_PATH should be enough. By the way what variables can be set to build only the `irods-runtime` and `irods-dev`?

Normally, you can get a list of targets by using tab completion on the call to `make` or `ninja`.

My guess is you can do something like the following:
```bash
make -j irods-dev irods-runtime
```

@SwooshyCueb Do you know of a better way to do this?

**Comment by korydraughn** [comment]
@ll4strw Please update the PR to only modify the `LD_LIBRARY_PATH`.

Please adjust the commit so that it resembles the following (leave off the pound until the PR is approved).
```
[6974] Fixed LD_LIBRARY_PATH for avrogencpp.
```

**Pull request merged**
