### PR TITLE
[#5224] Server removes leftover rulebase files on startup (master)

### PR DESCRIPTION
**Pull request by korydraughn**
Passed at bench.

### CODE REVIEW

**Comment by trel** [comment]
regex looks good.   this will match and remove `core.re.*` files, yes?   so also a partial fix for #4080?

**Comment by korydraughn** [comment]
yep. it removed the left over core.re.* files and fake.re.* files from my config dir

**Comment by trel** [comment]
cool - please reference it in the commit message alongside 5224.

then we'll # and merge

**Comment by korydraughn** [comment]
i added the issue number to the commit msg. is that what you meant?

**Comment by trel** [comment]
yeps - looks good.   # it.

**Comment by korydraughn** [comment]
Added #

**Pull request merged**
