### PR TITLE
[#7050] Fix statement leak (4-2-stable)

### PR DESCRIPTION
**Pull request by dworkin**

### CODE REVIEW

**Comment by trel** [comment]
excellent - is there a scenario (or even better, a test) that can trap/exhibit this leak?

**Comment by trel** [comment]
okay - thanks for the context.

**Review by alanking — COMMENTED** [review]
Yes, agreed. The same statement free is made just a few lines below for all of the "success" codepaths, so the failure codepath ought to do so as well.

@korydraughn / @trel - Shall I run this through the test gauntlet and call that sufficient, or should we think a little harder about how to add a test for this?

**Comment by trel** [comment]
definitely gauntlet - and bonus points for big thoughts or new tests.   but i don't know that they're necessary.

'by inspection' is a legitimate argument, just not as great as a test.

**Comment by alanking** [comment]
I tested this alongside #7062 and all the tests passed.

**Pull request merged**
