### PR TITLE
[#7844] `database_connect.py:get_odbc_driver_paths`: Update for MySQL 8.x and deprioritize MariaDB (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #7844

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good to me.

Do the unit tests still pass with MySQL 8?

**Comment by SwooshyCueb** [comment]
> Do the unit tests still pass with MySQL 8?

I don't think the full test suite is needed for this change. I did run a few tests though and they passed.

**Comment by korydraughn** [comment]
Agreed. As long as you were able to stand it up and watch some tests pass, that's all that's needed.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
