### PR TITLE
[#5693] msiRenameLocalZoneCollection commits changes to database (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
by removing this test - now we don't appear to have a test that changes the zone name?

i don't see a substitute/replacement `iadmin modzone` test anywhere else in the suite.

**Comment by korydraughn** [comment]
I am planning on adding one. This currently passes CI on ub16/postgres. I'm waiting for MySQL now.

I have manually verified that the database is updated correctly. I will add a test and make sure it passes today.

**Comment by trel** [comment]
gotcha - thanks.    this is the last one(!).

**Comment by korydraughn** [comment]
passed CI

added #

**Pull request merged**
