### PR TITLE
[#4337] Remove audit trails (master)

### PR DESCRIPTION
**Pull request by alanking**
[CI tests running](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1931/) (already passed before, but made an extra change for audit trails removal)

Note: Returning const& for getters in auth_objects may break client code which is dependent on string copies (e.g. contrived, temporary auth object to get user_name).

Also, I did not remove anything from lib/core or from initializing/linking tables in GenQuery.

### CODE REVIEW

**Comment by trel** [comment]
Do we have a known instance of a client using the string copies?   Jargon or Python code?

**Comment by alanking** [comment]
Thinking on it a bit more, I don't think this will actually affect any existing code. Back to [the docs for std::string constructors](https://en.cppreference.com/w/cpp/string/basic_string/basic_string) with me.

**Comment by alanking** [comment]
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1933/)

**Comment by trel** [comment]
let's get it # and merged.   good stuff.

**Comment by alanking** [comment]
Done

**Pull request merged**
