### PR TITLE
add timing tests to the python suite (4-2-stable)

### PR DESCRIPTION
**Pull request by jassigill2000**

### CODE REVIEW

**Comment by trel** [comment]
seems good to me - does it work?

 if kory has another commit, we'll get this in too.

**Comment by jassigill2000** [comment]
yes it works.

**Comment by trel** [comment]
okay, thanks - holding for now.

**Comment by trel** [comment]
think about which issue to point this at

**Comment by trel** [comment]
does this close those issues?   or should we leave them in 4.2 Backlog?

**Comment by jassigill2000** [comment]
we may want to pull them back where they belong once we move to Kubernetes. So I guess we leave them in the backlog.

**Comment by trel** [comment]
agreed

**Comment by jassigill2000** [comment]
added the # sign

**Pull request merged**
