### PR TITLE
[#6320] for PREP, adapt test user for 6 tests, skip others ... (main)

### PR DESCRIPTION
**Pull request by d-w-moore**
related to #5927 within class `irods.test.test_all_rules.Test_msiDataObjRepl_checksum_keywords`.

These tests are related to issue #5927 and are apparently failing for main branch whereas they are not failing for 4-2-stable (@alanking)

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good to me. Is there an issue with which to link this? @trel, would it make more sense to use the PREP repo for the commit message(s)?

**Comment by alanking** [comment]
I think using #5927 is fine. It will make the tests introduced there compliant with requirements for PREP, which was never really confirmed.

Also, @d-w-moore, when you say the tests are "apparently failing for main branch whereas they are not failing for 4-2-stable", are you referring to PREP or irods? The tests pass on main and 4-2-stable for irods proper (last time I tried, anyway), so I assume you mean PREP. I never confirmed that the tests worked on 4-2-stable for PREP, so I would assume they are broken there as well?

**Comment by d-w-moore** [comment]
@trel - these edits aren't related to #5927, but they allow 6 of the 12 tests to pass under PREP by adjusting the running user to be admin rather than user0 for that case....

@alanking I'll have to check if these work for PREP on 4-2-stable. I haven't done that either, only exploratively looked at output coming out of the 6-of-12 tests that are still failing despite my edits in the above commit.

**Comment by d-w-moore** [comment]
@alanking Yep, the 6 of 12 still failing on main actually do fail on 4-2-stable as well when PREP is the only rule engine active.

In summary , the purpose of this PR is
  - to correct the other 6 of the 12 not listed in #6320, for which the target of the PREP irule invocation merely needed to be changed to a rodsadmin and thus letting them pass
  - to skip the ones mentioned in #6320, so that a green is possible.  As @korydraughn has said, this is probably less important than some other issues.  These 6 are failing mainly because the messages coming back from the server call are not as expected / asserted

**Review by alanking — COMMENTED** [review]
New changes look good. Are we expecting more? If so, please mark this as draft and mark as ready for review once all the changes are in. If not, please adjust commit message(s) to reflect linked issues. Thanks!

**Comment by d-w-moore** [comment]
I've marked it as draft, until I have a chance to test again.

**Comment by d-w-moore** [comment]
ok, that last commit  "make re_serialization tests more robust for rsyslog and Py3 is not relevant except for 4.3.0, moving it to #6335

**Comment by d-w-moore** [comment]
This works now on Centos7

**Comment by d-w-moore** [comment]
This PR is  ready to merge, at least in spirit. It can be followed by up by, in this order:
   - https://github.com/irods/irods/pull/6335
   - https://github.com/irods/irods/pull/6324

And by this one in PREP:
   - https://github.com/irods/irods_rule_engine_plugin_python/pull/114

All the above PRs have been tested together as a unit and pass on [ Ubuntu18.04 / iRODS 4.3.0 ] Python RE plugin test.

**Comment by d-w-moore** [comment]
#'d

**Pull request merged**
