### PR TITLE
Catalog schema bump and setup script improvements (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by korydraughn** [comment]
I've confirmed the upgrade logic for the MySQL sequence number function is updated correctly.

### Fresh install of 4.3.0

The contents of the mysql_functions.sql file:
```sql
root@3df87d9bb26a:/# cat /var/lib/irods/packaging/sql/mysql_functions.sql                
drop function if exists R_ObjectId_nextval;                                              
delimiter %%                                                                             
create function R_ObjectId_nextval()                                                     
returns bigint                                                                           
begin                                                                                    
   insert into R_ObjectId_seq_tbl values (NULL) ;                                        
   set @R_ObjectId_val=LAST_INSERT_ID() ;                                                
   delete from R_ObjectId_seq_tbl ;                                                      
   return @R_ObjectId_val ;                                                              
end                                                                                      
%%                                                                                       
delimiter ;                                                                              
                                                                                         
drop function if exists R_ObjectId_currval;                                              
create function R_ObjectId_currval() returns bigint deterministic return @R_ObjectId_val;
```

The custom function just above, but stored in the MySQL database:
```sql
mysql> show function status like '%R_ObjectId_nextval%';
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| Db   | Name               | Type     | Definer | Modified            | Created             | Security_type | Comment | character_set_client | collation_connection | Database Collation |
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| ICAT | R_ObjectId_nextval | FUNCTION | irods@% | 2023-08-01 12:06:42 | 2023-08-01 12:06:42 | DEFINER       |         | utf8mb4              | utf8mb4_0900_ai_ci   | utf8mb4_0900_as_cs |
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
1 row in set (0.01 sec)

mysql> select * from INFORMATION_SCHEMA.ROUTINES where routine_name = 'R_ObjectId_nextval';
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
| SPECIFIC_NAME      | ROUTINE_CATALOG | ROUTINE_SCHEMA | ROUTINE_NAME       | ROUTINE_TYPE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_NAME | COLLATION_NAME | DTD_IDENTIFIER | ROUTINE_BODY | ROUTINE_DEFINITION                                                                                                                                                    | EXTERNAL_NAME | EXTERNAL_LANGUAGE | PARAMETER_STYLE | IS_DETERMINISTIC | SQL_DATA_ACCESS | SQL_PATH | SECURITY_TYPE | CREATED             | LAST_ALTERED        | SQL_MODE                                                                                                              | ROUTINE_COMMENT | DEFINER | CHARACTER_SET_CLIENT | COLLATION_CONNECTION | DATABASE_COLLATION |
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
| R_ObjectId_nextval | def             | ICAT           | R_ObjectId_nextval | FUNCTION     | bigint    |                     NULL |                   NULL |                19 |             0 |               NULL | NULL               | NULL           | bigint         | SQL          | begin
   insert into R_ObjectId_seq_tbl values (NULL) ;
   set @R_ObjectId_val=LAST_INSERT_ID() ;
   delete from R_ObjectId_seq_tbl ;
   return @R_ObjectId_val ;
end |          NULL | SQL               | SQL             | NO               | CONTAINS SQL    |     NULL | DEFINER       | 2023-08-01 12:06:42 | 2023-08-01 12:06:42 | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |                 | irods@% | utf8mb4              | utf8mb4_0900_ai_ci   | utf8mb4_0900_as_cs |
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
1 row in set (0.01 sec)
```

### After Upgrading

The mysql_functions.sql file _(notice the **where** clause of the **delete** line)_:
```sql
root@3df87d9bb26a:/host_irods_pkgs# cat /var/lib/irods/packaging/sql/mysql_functions.sql 
drop function if exists R_ObjectId_nextval;
delimiter %%
create function R_ObjectId_nextval()
returns bigint
begin
   insert into R_ObjectId_seq_tbl values (NULL) ;
   set @R_ObjectId_val=LAST_INSERT_ID() ;
   delete from R_ObjectId_seq_tbl where nextval = @R_ObjectId_val ;
   return @R_ObjectId_val ;
end
%%
delimiter ;

drop function if exists R_ObjectId_currval;
create function R_ObjectId_currval() returns bigint deterministic return @R_ObjectId_val;
```

When starting the server, the following is printed:
```bash
irods@3df87d9bb26a:~$ ./irodsctl -v start
Updating /var/lib/irods/version.json...
Validating [/etc/irods/server_config.json]... Success
Validating [/var/lib/irods/version.json]... Success
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Ensuring catalog schema is up-to-date...
Updating to schema version 10...
Updating to schema version 11...
Catalog schema is up-to-date.
Starting iRODS server ...
Succes
```

And here's the updated custom function stored in the MySQL database:
```sql
mysql> show function status like '%R_ObjectId_nextval%';
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| Db   | Name               | Type     | Definer | Modified            | Created             | Security_type | Comment | character_set_client | collation_connection | Database Collation |
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
| ICAT | R_ObjectId_nextval | FUNCTION | irods@% | 2023-08-01 12:36:41 | 2023-08-01 12:36:41 | DEFINER       |         | utf8mb4              | utf8mb4_0900_ai_ci   | utf8mb4_0900_as_cs |
+------+--------------------+----------+---------+---------------------+---------------------+---------------+---------+----------------------+----------------------+--------------------+
1 row in set (0.00 sec)

mysql> select * from INFORMATION_SCHEMA.ROUTINES where routine_name = 'R_ObjectId_nextval';
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
| SPECIFIC_NAME      | ROUTINE_CATALOG | ROUTINE_SCHEMA | ROUTINE_NAME       | ROUTINE_TYPE | DATA_TYPE | CHARACTER_MAXIMUM_LENGTH | CHARACTER_OCTET_LENGTH | NUMERIC_PRECISION | NUMERIC_SCALE | DATETIME_PRECISION | CHARACTER_SET_NAME | COLLATION_NAME | DTD_IDENTIFIER | ROUTINE_BODY | ROUTINE_DEFINITION                                                                                                                                                                                    | EXTERNAL_NAME | EXTERNAL_LANGUAGE | PARAMETER_STYLE | IS_DETERMINISTIC | SQL_DATA_ACCESS | SQL_PATH | SECURITY_TYPE | CREATED             | LAST_ALTERED        | SQL_MODE                                                                                                              | ROUTINE_COMMENT | DEFINER | CHARACTER_SET_CLIENT | COLLATION_CONNECTION | DATABASE_COLLATION |
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
| R_ObjectId_nextval | def             | ICAT           | R_ObjectId_nextval | FUNCTION     | bigint    |                     NULL |                   NULL |                19 |             0 |               NULL | NULL               | NULL           | bigint         | SQL          | begin
   insert into R_ObjectId_seq_tbl values (NULL) ;
   set @R_ObjectId_val=LAST_INSERT_ID() ;
   delete from R_ObjectId_seq_tbl where nextval = @R_ObjectId_val ;
   return @R_ObjectId_val ;
end |          NULL | SQL               | SQL             | NO               | CONTAINS SQL    |     NULL | DEFINER       | 2023-08-01 12:36:41 | 2023-08-01 12:36:41 | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |                 | irods@% | utf8mb4              | utf8mb4_0900_ai_ci   | utf8mb4_0900_as_cs |
+--------------------+-----------------+----------------+--------------------+--------------+-----------+--------------------------+------------------------+-------------------+---------------+--------------------+--------------------+----------------+----------------+--------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-------------------+-----------------+------------------+-----------------+----------+---------------+---------------------+---------------------+-----------------------------------------------------------------------------------------------------------------------+-----------------+---------+----------------------+----------------------+--------------------+
1 row in set (0.01 sec)
```

**Comment by trel** [comment]
no need - just add a `-f` instead.

https://github.com/irods/irods/issues/7239#issuecomment-1660603939

**Comment by korydraughn** [comment]
The `-f` worked.

```bash
root@2e6a889f2377:/host_irods_pkgs# dpkg -i irods-runtime_4.3.0-1~focal_amd64.deb irods-icommands_4.3.0-1~focal_amd64.deb irods-server_4.3.0-1~focal_amd64.deb irods-database-plugin-mysql_4.3.0-1~focal_amd64.deb 
(Reading database ... 34522 files and directories currently installed.)
Preparing to unpack irods-runtime_4.3.0-1~focal_amd64.deb ...
Unpacking irods-runtime (4.3.0-1~focal) over (4.3.0-1~focal) ...
Preparing to unpack irods-icommands_4.3.0-1~focal_amd64.deb ...
Unpacking irods-icommands (4.3.0-1~focal) over (4.3.0-1~focal) ...
Preparing to unpack irods-server_4.3.0-1~focal_amd64.deb ...
Server pidfile missing or stale. No iRODS server running?
Upgrading Existing iRODS Installation
Unpacking irods-server (4.3.0-1~focal) over (4.3.0-1~focal) ...
Preparing to unpack irods-database-plugin-mysql_4.3.0-1~focal_amd64.deb ...
Unpacking irods-database-plugin-mysql (4.3.0-1~focal) over (4.3.0-1~focal) ...
Setting up irods-runtime (4.3.0-1~focal) ...
Setting up irods-icommands (4.3.0-1~focal) ...
Setting up irods-server (4.3.0-1~focal) ...
Setting up irods-database-plugin-mysql (4.3.0-1~focal) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
root@2e6a889f2377:/host_irods_pkgs# su - irods -c './irodsctl -v start'
Updating /var/lib/irods/version.json...
Validating [/etc/irods/server_config.json]... Success
Validating [/var/lib/irods/version.json]... Success
Validating [/var/lib/irods/.irods/irods_environment.json]... Success
Ensuring catalog schema is up-to-date...
Updating to schema version 10...
Updating to schema version 11...
Catalog schema is up-to-date.
Starting iRODS server ...
Success
root@2e6a889f2377:/host_irods_pkgs# su - irods -c 'cat version.json'
{
    "catalog_schema_version": 11,
    "commit_id": "0d28b1dbd20e4d04c0cee879513401dd1c376a74",
    "installation_time": "2023-08-01T20:57:30.776758",
    "irods_version": "4.3.0",
    "previous_version": {
        "catalog_schema_version": 9,
        "commit_id": "f6eb6c72786288878706e2562a370b91b7d0802e",
        "installation_time": "2023-08-01T20:55:54.817865",
        "irods_version": "4.3.0",
        "schema_name": "version",
        "schema_version": "v4"
    },
    "schema_name": "version",
    "schema_version": "v4"
}
```

**Comment by korydraughn** [comment]
The only item remaining for this PR is to verify the unattended installation works when `default_resource_name` is not defined in server_config.json.

**Comment by korydraughn** [comment]
I've verified that unattended installations work without `default_resource_name`.

There were some issues with shutting down the server (i.e. zombie processes), but that's because there was no init process in the container I used.

I also learned the iRODS server package does not list unixodbc as a dependency. That resulted in pyodbc reporting the following:
```bash
root@6eab564f5794:/# python3 /var/lib/irods/scripts/setup_irods.py --json_configuration_file ./input.provider                                                                                 
Warning: Hostname `6eab564f5794` should be a fully qualified domain name.
Error encountered running setup_irods:                                                                                                                                                        
Traceback (most recent call last):                                                    
  File "/var/lib/irods/scripts/irods/database_connect.py", line 206, in get_database_connection   
    conn = pyodbc.connect(connection_string, ansi=True)                                                                                                                                       
pyodbc.OperationalError: ('08001', '[08001] could not translate host name "catalog" to address: Name or service not known\n (101) (SQLDriverConnect)')                                        
                                                                                               
During handling of the above exception, another exception occurred:
                                                                                                                                                                                              
Traceback (most recent call last):                     
  File "/var/lib/irods/scripts/setup_irods.py", line 515, in main                   
    setup_server(irods_config,                                                                                                                                                                                                                                                                                                                                                               
  File "/var/lib/irods/scripts/setup_irods.py", line 134, in setup_server
    database_interface.setup_catalog(irods_config, default_resource_directory=default_resource_directory, default_resource_name=default_resource_name)                                        
  File "/var/lib/irods/scripts/irods/database_interface.py", line 19, in setup_catalog
    with contextlib.closing(database_connect.get_database_connection(irods_config)) as connection:                                                                                            
  File "/var/lib/irods/scripts/irods/database_connect.py", line 238, in get_database_connection                                                                                               
    six.reraise(IrodsError,                                 
  File "/var/lib/irods/scripts/irods/six.py", line 671, in reraise                                                                                                                                                                                                                                                                                                                           
    raise value.with_traceback(tb)                                           
  File "/var/lib/irods/scripts/irods/database_connect.py", line 206, in get_database_connection                                                                                               
    conn = pyodbc.connect(connection_string, ansi=True)                      
irods.exceptions.IrodsError: pyodbc encountered an error connecting to the database:
('08001', '[08001] could not translate host name "catalog" to address: Name or service not known\n (101) (SQLDriverConnect)')
```
I eventually installed unixodbc and replaced the reference to `catalog` with the container hostname in the database stanza of the input file. For some reason, connecting to the database still failed. Changing the database stanza to use localhost worked though.

Ultimately, we need to have some automated testing for unattended installs. It is very tedious to have to redo everything whenever there's a problem.

I think this PR is ready for the green light.

**Comment by trel** [comment]
The unixodbc dependency is on the database plugins, yes?

**Comment by korydraughn** [comment]
After I installed the packages (the postgres database plugin package included), I ran `apt install -fy` and that did not result in unixodbc being installed.

**Comment by trel** [comment]
@SwooshyCueb did we lose the dependency along the way?

Can we pinpoint when that happened?  Maybe we're forgetting why?

**Comment by SwooshyCueb** [comment]
unixodbc was replaced with libodbc1. See #5962

**Comment by korydraughn** [comment]
Added new commit to address unixodbc dependency for debian-based OS.

**Review by alanking — APPROVED** [review]
Looks good to me

**Review by SwooshyCueb — APPROVED** [review]

**Comment by korydraughn** [comment]
Added #'s

**Pull request merged**
