### PR TITLE
[#3998] Restore rei->msParamArray in remoteExec (master)

### PR DESCRIPTION
**Pull request by alanking**
rei->msParamArray is used in smsi_remoteExec for remote execution and clears the contents after completing. This was being done in the past because state was being stored in the rule execution environment and was used to populate rei.

This has changed as of ced5dd3121ea49fa017bd29e643ab7ac287d30eb.
rei->msParamArray needs to be preserved for code executing after remoteExec.

---
[CI tests passed.](http://172.25.14.125:8080/job/irods-build-and-test-workflow/1110/) Implementation based on smsi_delayExec a few lines above these changes.

### CODE REVIEW

**Comment by jaking92** [comment]
Per observation from Hao, this is still missing some functionality. Hold off on merging for now.

**Comment by jaking92** [comment]
I believe I have addressed Hao's concerns, but we have additional questions about stdout. Opened #4018 for this. Let me know if there's anything else we want to do with these changes.

**Comment by trel** [comment]
@xu-hao can you take a look?   if no other concerns, we'll add the # and get it merged.

**Comment by trel** [comment]
have a one line example?

**Comment by jaking92** [comment]
Codacy doesn't know about **locals(), so let me know if you want me to fix that up.

Otherwise, awaiting input from @xu-hao (whenever you are able). Also need the #'s. Thanks!

**Comment by trel** [comment]
@xu-hao does this look good to you?

**Comment by trel** [comment]
add some # and we'll get it merged

**Comment by alanking** [comment]
[CI tests passed](http://172.25.14.63:8080/view/Personal/job/irods-build-and-test-workflow/1634/) ([ran ub16-mysql again](http://172.25.14.63:8080/job/test-ub16-mysql/936/) because of CI hiccup)

**Pull request merged**
