### PR TITLE
[#7281] Fix RPM package dependencies (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Potentially breaking changes:
- Centos 7 server package now explicitly depends on `python36-` packages. `yum` isn't always able to bridge the gap between a `python3-` dependency declaration and the `python36-` package that satisfies it. However, this might make upgrading from EL7 to a later EL a little tricky.
- On EL8+, the mysql/mariadb db plugin has dropped the `mysql` dependency declaration for `mariadb` to match the ODBC connector dependency declaration. If we have to make the choice between locking someone into using mysql or mariadb, the choice should be mariadb IMO. (Not to imply this *does* lock anyone into anything.)

Still in need of some testing. Some assistance with that would be appreciated, particularly for the mysql/mariadb db plugin.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
When it comes to the mysql/mariadb db plugin, I want to make sure that it still works with both mysql and maraidb on EL8+, both remotely and in the same system/container.
Just some basic iputs and igets will be enough to satisfy me.

Quick note, the testing environment does not currently support mariadb, and it only does remote db connections as it spins up separate docker containers for the db.

**Comment by korydraughn** [comment]
Going to run all unit tests and core tests for cen7 just so we're sure things are good.

If no one else does it, I'll do the same for alma8.

**Comment by korydraughn** [comment]
The unit tests failed with the following.

I have a fix in the works for this one. Created #7289 for it.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="irods_lifetime_manager" errors="0" failures="1" tests="25" hostname="tbd" time="0.000" timestamp="2023-08-28T14:12:28Z">
    <testcase classname="irods_lifetime_manager.global" name="test_dataObjInfo_t" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_keyValPair_t" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_rodsObjStat_t" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_bytesBuf_t" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_rError_t" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_delete" time="0.000" status="run">
      <failure message="str == t->str()" type="REQUIRE">
FAILED:
  REQUIRE( str == t->str() )
with expansion:
  "this is also a test"
  ==
  "this is also a testt"
  ==!"
at /irods_source/unit_tests/src/test_irods_lifetime_manager.cpp:126
      </failure>
    </testcase>
    <testcase classname="irods_lifetime_manager.global" name="test_release" time="0.000" status="run"/>
    <testcase classname="irods_lifetime_manager.global" name="test_array_delete/normal" time="0.000" status="run"/>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```

This one will take a little extra work to figure out why it's failing.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite errors="0" failures="3" tests="5" hostname="tbd" time="0.268" timestamp="2023-08-28T14:12:28Z">
    <testcase classname="irods_rc_check_auth_credentials.global" name="rc_check_auth_credentials basic functionality" time="0.000" status="run"/>
    <testcase classname="irods_rc_check_auth_credentials.global" name="rc_check_auth_credentials basic functionality/rc_check_auth_credentials basic functionality" time="0.000" status="run">
      <failure message="rc_check_auth_credentials(conn_ptr, &amp;input, &amp;correct) == 0" type="CHECK">
FAILED:
  CHECK( rc_check_auth_credentials(conn_ptr, &amp;input, &amp;correct) == 0 )
with expansion:
  -167000 == 0
at /irods_source/unit_tests/src/test_rc_check_auth_credentials.cpp:54
      </failure>
      <failure message="correct" type="CHECK">
FAILED:
  CHECK( correct )
with expansion:
  nullptr
at /irods_source/unit_tests/src/test_rc_check_auth_credentials.cpp:55
      </failure>
      <error message="{Unknown expression after the reported line}">
FAILED:
  {Unknown expression after the reported line}
SIGSEGV - Segmentation violation signal
at /irods_source/unit_tests/src/test_rc_check_auth_credentials.cpp:55
      </error>
    </testcase>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```
This also resulted in the following appearing in the server log file. Notice the ODBC error.
```json
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "Initializing server ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:25.969Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "Setting up UNIX domain socket for agent factory ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:25.975Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "Forking agent factory ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:25.976Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "Connecting to agent factory [agent_factory_pid=347] ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:25.977Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "agent_factory",
  "log_level": "info",
  "log_message": "Initializing agent factory ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 347,
  "server_timestamp": "2023-08-28T14:12:25.978Z",
  "server_type": "agent_factory",
  "server_zone": "tempZone"
}
{
  "local_hostname": "localhost, e3d3ad14b3b0",
  "log_category": "server",
  "log_level": "info",
  "port": "1247",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:26.047Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "server",
  "log_level": "info",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:26.074Z",
  "server_type": "server",
  "server_zone": "tempZone",
  "zone_info.host": "localhost",
  "zone_info.name": "tempZone",
  "zone_info.port": "1247",
  "zone_info.type": "LOCAL_ICAT"
}
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "rodsServer Release version rods4.3.0 - API Version d is up",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:26.075Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "legacy",
  "log_level": "info",
  "log_message": ">>> control plane :: listening on port 1248\n",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:26.077Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "server",
  "log_level": "info",
  "log_message": "Forking Delay Server (irodsDelayServer) ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 346,
  "server_timestamp": "2023-08-28T14:12:26.359Z",
  "server_type": "server",
  "server_zone": "tempZone"
}
{
  "log_category": "delay_server",
  "log_level": "info",
  "log_message": "Initializing delay server ...",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 360,
  "server_timestamp": "2023-08-28T14:12:26.392Z",
  "server_type": "delay_server",
  "server_zone": "tempZone"
}
{
  "log_category": "database",
  "log_level": "error",
  "log_message": "db_check_auth_credentials_op: /externals/nanodbc2.13.0-1_src/nanodbc/nanodbc/nanodbc.cpp:1443: 42S0: [MySQL][ODBC 8.0(a) Driver][mysqld-8.0.29]Table 'ICAT.r_user_main' doesn't exist ",
  "request_api_name": "CHECK_AUTH_CREDENTIALS_AN",
  "request_api_number": 800,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "10.15.3.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.0",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 430,
  "server_timestamp": "2023-08-28T14:12:28.966Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
{
  "log_category": "legacy",
  "log_level": "error",
  "log_message": "[-]\t/irods_source/server/core/src/rsApiHandler.cpp:565:int readAndProcClientMsg(rsComm_t *, int) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [failed to call 'read header']\n\t[-]\t/irods_source/lib/core/src/sockComm.cpp:229:irods::error readMsgHeader(irods::network_object_ptr, msgHeader_t *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR
]  errno [] -- message [failed to call 'read header']\n\t\t[-]\t/irods_source/plugins/network/src/tcp.cpp:190:irods::error tcp_read_msg_header(irods::plugin_context &, void *, struct timeval *) :  status [SYS_HEADER_READ_LEN_ERR]  errno [] -- message [only read [0] of [4]]\n\n",
  "request_api_name": "CHECK_AUTH_CREDENTIALS_AN",
  "request_api_number": 800,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "10.15.3.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.0",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 430,
  "server_timestamp": "2023-08-28T14:12:29.160Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
{
  "log_category": "agent",
  "log_level": "error",
  "log_message": "Agent [430] exiting with status = -4000",
  "request_api_name": "CHECK_AUTH_CREDENTIALS_AN",
  "request_api_number": 800,
  "request_api_version": "d",
  "request_client_user": "rods",
  "request_host": "10.15.3.5",
  "request_proxy_user": "rods",
  "request_release_version": "rods4.3.0",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 430,
  "server_timestamp": "2023-08-28T14:12:29.160Z",
  "server_type": "agent",
  "server_zone": "tempZone"
}
{
  "log_category": "agent_factory",
  "log_level": "error",
  "log_message": "Agent process [430] exited with status [1].",
  "server_host": "e3d3ad14b3b0",
  "server_pid": 347,
  "server_timestamp": "2023-08-28T14:12:29.170Z",
  "server_type": "agent_factory",
  "server_zone": "tempZone"
}
```

**Comment by korydraughn** [comment]
I've found the issue with the other test. The database plugin has a small SQL bug specific to MySQL.

Both issues reported here have nothing to do with the work in this PR. Will fix them and proceed with testing this PR.

**Comment by korydraughn** [comment]
The changes in PR #7291 resolve the reported issues.

All unit tests pass.

Running core tests now.

**Comment by korydraughn** [comment]
Core tests finally passed for CentOS 7.

Moving to Almalinux 8.

**Comment by korydraughn** [comment]
All unit tests pass for Almalinux 8 (ignoring the ones known to fail).

Running core tests.

**Comment by korydraughn** [comment]
All core tests passed for Almalinux 8 / MySQL 8 (separate containers).

Will look into standing up Alamlinux 8 / MySQL 8 within the same container/VM.

**Comment by korydraughn** [comment]
MariaDB status update ...

I've confirmed (through manual testing) that the MariaDB ODBC connector works for Almalinux 8, **sort of**.

The case I'm describing is:
- The database and iRODS provider are on different computers (specifically, in separate containers)
- The database is MySQL 8
- The iRODS server is using the mariadb-connector-odbc package provided by the OS
    - Keep in mind, this is defined as a dependency by the iRODS MySQL database plugin

I confirmed this by doing the following:
1. Launched an iRODS zone (w/ Almalinux 8 and MySQL 8) using the testing environment.
   - I used the stand_it_up.py script
3. Stopped the iRODS server.
4. Ran `dnf repoquery --requires irods-database-plugin-mysql` to confirm the mariadb-connector-odbc package is listed as a dependency.
5. Ran `find /usr/lib64 -name libmaodbc.so` to confirm the shared library for the ODBC connector was installed.
6. Made a copy of `/etc/odbcinst.ini` in case I screwed something up.
7. Replaced the contents of `/etc/odbcinst.ini` with the following:
```
[MariaDB]
Description = MariaDB driver
Driver = /usr/lib64/libmaodbc.so
```
8. Updated the database stanza in `/etc/irods/server_config.json` to use `MariaDB` instead of `MySQL ANSI`.
9. Launched the iRODS server.
   - Confirmed the driver was being picked up by looking at the contents of `.odbc.ini`
   - `.odbc.ini` in the service account's home directory is overwritten with information from `server_config.json` every time the iRODS server is started
   - `.odbc.ini` will always use the driver name defined by `server_config.json` 
11. Ran `echo data | istream write foo` and it succeeded.
    - `ils` and `istream read foo` printed the correct information to the terminal
12. Ran `iput version.json goo` and that succeeded, but resulted in `CAT_SUCCESS_BUT_WITH_NO_INFO` being printed to the terminal.
    - `iget goo -` does not report an error
13. Ran `irm foo` and that succeeded, but resulted in the same message that `iput` generated.
    -  Running `irmtrash` and `irm -f` did not cause the message to appear

**So something is different.** While the operations appear to work, some operations cause `CAT_SUCCESS_BUT_WITH_NO_INFO` to be returned. It could be that the `.odbc.ini` in the service account's home directory needs some MariaDB specific options.

**Comment by trel** [comment]
That sounds like a potentially slightly different return code coming back from the ODBC driver.

**Comment by korydraughn** [comment]
That could be the case. It certainly makes sense given we're using a different driver.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
After some discussion, we've agreed that this PR is safe.

Although the database plugin declares mariadb-connector-odbc as a dependency, admins are free to use something different (i.e. a MySQL ODBC driver).

The comments regarding the MariaDB ODBC driver have been captured in #7323 and will be addressed in a later release.

**Review by alanking — APPROVED** [review]

**Pull request merged**
