### PR TITLE
[4063] Ensure AVUs set properly (main)

### PR DESCRIPTION
**Pull request by MartinFlores751**
Cherry-pick of #6920.

### CODE REVIEW

**Comment by korydraughn** [comment]
Needs more clang-format.

**Comment by alanking** [comment]
Ah, missed that on the 4-3-stable. Please backport those changes once this is merged. Sorry about that.

**Review by korydraughn — COMMENTED** [review]
Looks good. Please squash and leave off the pounds.

**Review by alanking — APPROVED** [review]

**Review by korydraughn — APPROVED** [review]
Add the pound.

**Pull request merged**
