### PR TITLE
Fixed memory leaks and realloc bug in Pack Struct (master)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
oh my.

**Comment by korydraughn** [comment]
all tests passed except the irodsctl tests.

**Comment by trel** [comment]
thoughts on the irodsctl tests not passing?    is that known?

**Comment by korydraughn** [comment]
I'm not surprised. I've been seeing validation issues on startup quite a bit. I know Jason brought it up a while back as well. I think it has to do with cmake/cpack and how paths are generated. With that said, I don't think it should stop anything from being merged.

**Comment by trel** [comment]
okay - so perhaps some build artifacts.

it's green - let's # em.

**Comment by korydraughn** [comment]
added #

**Pull request merged**
