### PR TITLE
Use proxy objects in rsDataObjClose + New replica/data_object features (master)

### PR DESCRIPTION
**Pull request by alanking**
Making boundaries for logical locking more clear by refactoring rsDataObjClose a bit. Some other library features needed for logical locking as well.

CI tests passed except for one, which was fixed and passed at the bench.

### CODE REVIEW

**Comment by trel** [comment]
two codacy thingers - otherwise, squash and # when happy

**Comment by alanking** [comment]
The Codacy issues have been addressed with the use of static_cast, so I'm not sure why it is still complaining.

**Comment by trel** [comment]
you fixed two, it found two others - different line numbers it seems

**Comment by trel** [comment]
green codacy, please to #

**Comment by alanking** [comment]
#'d

**Pull request merged**
