### PR TITLE
[#3848] Implement irods::logical_locking (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Cherry-picked from changes in #5539 

CI tests running

### CODE REVIEW

**Comment by trel** [comment]
green build - please # if they pass

**Comment by alanking** [comment]
1 test failed in CI, but the latest change should address this. Running test now

**Comment by alanking** [comment]
The affected test now passes.

**Comment by trel** [comment]
then # with confidence!   titles and bodies.

**Comment by alanking** [comment]
#'d

**Pull request merged**
