### PR TITLE
[#5675] Set L1desc input data size for put (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
cherry-picked from work done for #5676 

CI tests running soon...

### CODE REVIEW

**Comment by trel** [comment]
in the first commit message...

multithreded -> multithreaded

**Comment by alanking** [comment]
Argh. Will fix when ready for #

**Comment by trel** [comment]
yes, please # when CI is happy.

**Comment by alanking** [comment]
CI tests passed. #'d

**Pull request merged**
