### PR TITLE
[#5193] Mark newly created replicas as good with no bytes written (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
CI tests running.

A note about the TODO: This is technically incorrect as we need to check for the expected size of the replica before we determine that it is good. This PR will restore the historical behavior of assuming new replicas with no bytes written are good. Future changes will require more vetting with respect to the expected size of the replica.

### CODE REVIEW

**Comment by alanking** [comment]
Another note - if something goes wrong with the checksum process for PUTs here, the replica will be stuck in the intermediate state instead of moving to the stale state. This behavior will be overwritten in a future commit, but adding this here in case it comes up later.

**Comment by trel** [comment]
looks fine to me - let's # it and get dan happy.

**Comment by d-w-moore** [comment]
@alanking , great, thanks! in my repo now and building

**Comment by d-w-moore** [comment]
thanks @trel yes, merge at leisure and I'll test based on what I've imported from alan's 4-2-stable branch . ... I'm sure the SHA's will match up when I check'em later....

**Comment by alanking** [comment]
Had 1 test fail in CI but passes at the bench.

**Pull request merged**
