### PR TITLE
[#4310] Added script that configures rsyslog, logrotate, etc. (master)

### PR DESCRIPTION
**Pull request by korydraughn**
- Fixed preinst script bug: "upgrade.tmp" was not being created.

### CODE REVIEW

**Comment by trel** [comment]
looks good - please add #

**Comment by korydraughn** [comment]
Added #.

**Comment by korydraughn** [comment]
Please hold on this PR.

**Comment by korydraughn** [comment]
This PR is all good now.  I found an issue where the log messages were still going to **/var/log/syslog** even though they were going to **/var/log/irods/*.log** already.  The fix required adding a new **& stop** command to the rsyslog config.

**Pull request merged**
