### PR TITLE
[#7759] Stamp iRODS version number on sister project packages (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #7759

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look good/normal.

I take it this only adds the iRODS version to the package metadata, correct?

**Comment by SwooshyCueb** [comment]
package metadata and package filename

**Comment by trel** [comment]
So when someone specifies a particular version to install... would they have to type/specify this new information?

aka `apt install irods-server=xxxxxx`

**Comment by SwooshyCueb** [comment]
> So when someone specifies a particular version to install... would they have to type/specify this new information?
> 
> aka `apt install irods-server=xxxxxx`

Only in cases where the package revision was already needed. If they weren't typing `~jammy` or `.el8` before, they won't have to worry about this.
Also, this doesn't affect the irods-server package.

**Comment by trel** [comment]
Right, I realized irods-server was immune as soon as I hit enter.

Going farther afield...  is there a future where they don't have to specify the longer `~jammy` or `.el8` suffix, and can get back to just the dotted-number?

**Comment by korydraughn** [comment]
@trel Any additional comments to add for this?

So in the future, users who want to install a specific version of a sister project will need to include the `+<irods_version>` suffix in the version string.

I'm wondering if that's worth documenting in docs.irods.org or whether the release notes are enough.

@SwooshyCueb Are there conventions for handling that?

**Comment by SwooshyCueb** [comment]
> So in the future, users who want to install a specific version of a sister project will need to include the `+<irods_version>` suffix in the version string.

Only on Debian and Ubuntu.

> I'm wondering if that's worth documenting in docs.irods.org or whether the release notes are enough.

apt has always required the full package version, including package revision string when specifying a version of a package to install. We started adding proper package revision strings to our package versions a while back, so I don't think any new documentation is needed. We can say something about the change in our release notes, but, in my opinion, if someone wants to learn how their package manager works, they should consult their package manager's documentation, not ours.

**Comment by korydraughn** [comment]
Yep, makes sense.

The release notes are the place to inform people of the change.

**Review by korydraughn — APPROVED** [review]
Let's get one more approval before adding the pound.

**Review by trel — APPROVED** [review]
looks complete

**Comment by korydraughn** [comment]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
