### PR TITLE
[#6918] Correct msiAddKeyVal behavior (4-3-stable)

### PR DESCRIPTION
**Pull request by MartinFlores751**
Cherry-pick of #7049. All tests passed!

### CODE REVIEW

**Comment by korydraughn** [comment]
Did you have to change anything following the cherry-pick?

**Comment by MartinFlores751** [comment]
Nope, just rebased after some more commits were pushed to 4-3.

**Comment by trel** [comment]
are we ignoring the clang-format opinions here?

**Comment by korydraughn** [comment]
Oh yeah, please run clang-format on the changes.

**Comment by trel** [comment]
nice.   and the clag-tidy issues are not 'new'.   seems good to me.

**Review by korydraughn — COMMENTED** [review]
Looks good to me.

Please squash to taste and leave off the pounds.

**Review by alanking — APPROVED** [review]
Looks good

**Review by korydraughn — APPROVED** [review]
Add the pound when ready.

**Review by alanking — APPROVED** [review]

**Pull request merged**
