### PR TITLE
[#6887] allow igroupadmin mkuser to initialize the new user's password (4-3-stable)

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by d-w-moore** [comment]
Corresponds to https://github.com/irods/irods_client_icommands/pull/359

**Review by alanking — COMMENTED** [review]
Please be sure to apply clang-format changes as with #6889 and #6915. Otherwise looks good

**Comment by d-w-moore** [comment]
Done

**Review by alanking — APPROVED** [review]
Yes, please add #s

**Comment by d-w-moore** [comment]
Will do. I guess we're not caring about clang tidy yet, correct?

**Comment by alanking** [comment]
Making clang-tidy happy is not considered a blocker right now

**Review by korydraughn — APPROVED** [review]

**Comment by d-w-moore** [comment]
Done. Now with #.

**Pull request merged**
