### PR TITLE
[#6063] "rodsadmin" group is not created on new installs (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
this seems correct...

after a clean install, we should put here:
1) output of `iadmin lu`
2) output of `iadmin lg`
3) output from a clean test run

**Comment by trel** [comment]
let’s call it new install rather than vanilla.

**Comment by korydraughn** [comment]
updated title and commit message.

**Comment by trel** [comment]
looks good - please get output mentioned earlier here... and then # when ready/happy/confirmed.

**Comment by korydraughn** [comment]
i'm guessing we want to list the users/groups following the test put?

how do we feel about the following output:
```bash
iRODS Users:
  - user 1
  - user 2
  - ...
  - user N

iRODS Groups:
  - group 1
  - group 2
  - ...
  - group N
```
is this output needed if new installs only contain the `rods` user and `public` group?

maybe this output is better:
```bash
Registered iRODS Users : rods
Registered iRODS Groups: public
```

**Comment by korydraughn** [comment]
Output of requested commands following a new install.
```bash
$ iadmin lu
rods#tempZone
$ iadmin lg
public
```

**Comment by trel** [comment]
good for me.

**Comment by korydraughn** [comment]
I tried to run this through CI, but it fails on setup. I think we need to get the testing environment working with main.

**Comment by trel** [comment]
@alanking, consider pushing this through a basic testrun?

**Comment by trel** [comment]
oh, it says right there... main.    as you were.

**Comment by korydraughn** [comment]
added #

**Pull request merged**
