### PR TITLE
[7154] Change irods::file_object size to rodsLong_t (main)

### PR DESCRIPTION
**Pull request by Nishant2022**

### CODE REVIEW

**Comment by Nishant2022** [comment]
All unit tests pass

**Comment by Nishant2022** [comment]
Running them now

**Review by korydraughn — APPROVED** [review]
Great. Add the pound.

**Review by alanking — APPROVED** [review]
I took a look around and don't see many places where this is being used, let alone places where any resulting errors wouldn't be caught, so I think it is safe to merge.

**Pull request merged**
