### PR TITLE
Split up `test_catalog` and package unit tests with server (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
cherry-picked from work for #6182

still need to test

### CODE REVIEW

**Comment by alanking** [comment]
Ignoring the other Codacy issues as `self` is used by the `unittest` framework. Arguably, the underlying libraries for `assert_icommand` should not be using naked `assert`s but I'm not going to solve that here.

**Comment by trel** [comment]
seems good after squashin'

**Comment by trel** [comment]
please # and jam once green.

**Comment by alanking** [comment]
#'d. Jammin'.

**Pull request merged**
