### PR TITLE
[#7228] Fixed issues with apiPackTable.h (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Unit tests passed.

I don't think this needs to be run through the core tests. Behavior of server is unchanged.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks good. We can deal with potentially impacted clients/plugins as we approach release time, yes?

**Comment by trel** [comment]
yes, i only see two commits on PR 7273

**Comment by korydraughn** [comment]
If you go to my branch, you'll see 3.

**Comment by korydraughn** [comment]
I squashed and force-pushed to see what would happen.

**Review by SwooshyCueb — APPROVED** [review]

**Comment by korydraughn** [comment]
Clang-tidy is happy.

Adding pounds.

**Comment by korydraughn** [comment]
Added #'s

**Review by alanking — APPROVED** [review]

**Pull request merged**
