### PR TITLE
[5916,6674] Improve `rstrcpy` logging (4-3-stable)

### PR DESCRIPTION
**Pull request by MartinFlores751**
Update log level to show rstrcpy arguments, stop rstrcpy printing stacktrace

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks good. Does it compile and do what you want?

**Comment by MartinFlores751** [comment]
Will check and get back to you on that.

On a side note, I just noticed that 4-2-stable doesn't have the modern logging from what I see. Might need to use `rodsLog(...)` for that one?

**Comment by korydraughn** [comment]
> On a side note, I just noticed that 4-2-stable doesn't have the modern logging from what I see. Might need to use rodsLog(...) for that one?

Correct.

**Comment by MartinFlores751** [comment]
All but two tests passed for me, being *test_icd* and *test_iadmin*. Looking at the logs, I believe they may have been introduced by the PR irods/irods_client_icommands#331.

The failing `icd` test expects the following string: `No such directory (collection):` but the commit changed the string to `No such collection:`

On *test_iadmin* I'm seeing `NO_COLUMN_NAME_FOUND` twice and `CAT_INSUFFICIENT_PRIVILEGE_LEVEL`, but I haven't looked into the exact source of this problem yet. I don't believe that `rstrcpy(...)` caused this, though…

**Comment by korydraughn** [comment]
The `icd` failure sounds like a _fix the test_ kind of thing. If you're confident that is what it is, include a commit that fixes that test. You can use issue number 858 for things like that.

Please investigate the `iadmin` test failure and report what you find here. We can determine if that deserves a new issue based on what you find.

**Comment by alanking** [comment]
The `test_iadmin` failure is likely from the same PR.

An equivalent PR was opened for 4-3-stable here for the iCommands: https://github.com/irods/irods_client_icommands/pull/332

And the tests were adjusted in these two commits in the main repo:
https://github.com/irods/irods/pull/6637 (main)
https://github.com/irods/irods/pull/6654 (4-3-stable)

Please confirm that the built iCommands are on the right commit

**Comment by MartinFlores751** [comment]
Got it. My upstream was only tracking main for some reason? Going to run the full suite again, just in case.

**Comment by MartinFlores751** [comment]
All tests passed!

**Comment by korydraughn** [comment]
Add the pounds!

**Pull request merged**
