### PR TITLE
[#5700] Control plane uses server_config.json to resolve hostnames (main)

### PR DESCRIPTION
**Pull request by korydraughn**
running CI tests

### CODE REVIEW

**Comment by korydraughn** [comment]
experiencing very different CI testing issues for ubuntu 18 and centos 7.

ubuntu is having trouble building packages.
centos is failing to stand up the server.

4-2-stable branch did not have any issues.

**Comment by trel** [comment]
build seemed to go okay... (3 greens)

**Comment by korydraughn** [comment]
Yes. It builds from scratch and runs fine on my machine. Maybe an assumption has been broken in CI.

**Comment by trel** [comment]
oh, you're saying jenkins itself can't build this and get it installed.    yes, that's probably because we just changed some dependencies and package names/version numbers.

i think we're good to # this and get it merged.   we'll stare at CI in the near future.

**Comment by korydraughn** [comment]
im pretty sure this PR is good.

added #

**Pull request merged**
