### PR TITLE
Issue 6502 43 stable

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Comment by korydraughn** [comment]
Is this PR identical to #7021?

**Comment by JustinKyleJames** [comment]
> Is this PR identical to #7021?

Yes it is identical.  I just finished tests on it.

**Review by alanking — APPROVED** [review]
Let's # it.

**Review by korydraughn — APPROVED** [review]

**Comment by JustinKyleJames** [comment]
> Let's # it.

Done

**Pull request merged**
