### PR TITLE
[#7823] Update GitHub workflows for Ubuntu 24.04 (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of #7823

Also adds [.h,.c.,.hpp,.cpp].in files to clang-format extension list

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Waiting for github workflows to complete before approving.

**Comment by trel** [comment]
so much green.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
