### PR TITLE
[7979] Deprecate dataObjLock and dataObjUnlock (4-3-stable)

### PR DESCRIPTION
**Pull request by FifthPotato**
I think I hit all the relevant locations; feel free to comment if I missed anything.

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looking good so far.

**Review by korydraughn — APPROVED** [review]
Looks correct to me.

Please wait for another approval before squashing/pounding.

**Review by alanking — APPROVED** [review]
Squash and # it

**Comment by FifthPotato** [comment]
Squished and octothorpe'd.

**Pull request merged**
