### PR TITLE
actually read from the buffer returned by rcDataObjRead

### LINKED ISSUE #2503: _ifuseFileCacheRead does not actually read to buf when fileCache->state == NO_FILE_CACHE
For both current master and stable, if `fileCache->state == NO_FILE_CACHE`, _fuseFileCacheRead (in `iFuseLib.FileCache.cpp`) sets `dataObjReadOutBBuf.buf` to be the pointer `buf` specified in its constructor, but when `rcDataObjRead` is called, it eventually calls `read_bytes_buf` in libtcp.cpp, which re-mallocs the buf field of this struct, (line 503).

Upon return from `rcDataObjRead`, `dataObjReadOutBBuf.buf` is never copied back to `buf`.

### PR DESCRIPTION
**Pull request by bpow**
I believe this fixes #2503 (but I'm not sure if there isn't a better way)

### CODE REVIEW

**Comment by jasoncoposky** [comment]
i believe this is fixed in #2538, please confirm.

**Comment by bpow** [comment]
#2538 does appear to fix this. I would have responded earlier, but irodsFuse was broken again in the meantime so I could not verify (see #2554 for that issue and its proposed fix).

**Comment by trel** [comment]
Can you verify now?  We just fixed #2554 with your pull request.

**Comment by trel** [comment]
@bpow awaiting confirmation - will close soon.

**Comment by bpow** [comment]
Sorry about that. This is working for me now in the testing that I have
done, thanks.

**Pull request closed without merging**
