### PR TITLE
Enabled full access to Filesystem lib and dstream lib (4-3-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cherry-picked from #6790.

Running `git diff` on main and 4-3-stable results in this PR.

If compilation succeeds, we can assume that everything works as expected since this PR makes 4-3-stable identical to the main branch.

I'll run the unit tests and the microservice tests to make sure things are good.

### CODE REVIEW

**Comment by korydraughn** [comment]
All unit tests passed. The microservice tests for filesystem and dstream passed too.

Will add the pounds soon.

**Review by trel — APPROVED** [review]

**Comment by trel** [comment]
rocky8 is unhappy

**Comment by korydraughn** [comment]
The failure looks to be due to Rocky rather than this PR.

**Comment by trel** [comment]
agreed.   @alanking seen this before?

**Comment by alanking** [comment]
Yeah, I've never seen that. I made an issue here so we can look into it: https://github.com/irods/irods/issues/6852

**Review by alanking — APPROVED** [review]

**Comment by korydraughn** [comment]
Added #'s

**Pull request merged**
