### PR TITLE
[#7523,#7524,#7548,#7549] A smattering of CMake changes (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #7523
Addresses #7524
Addresses #7548
Addresses #7549

### CODE REVIEW

**Comment by korydraughn** [comment]
Is this identical to the PR for main?

**Comment by SwooshyCueb** [comment]
Yes

**Review by korydraughn — APPROVED** [review]
Pound it.

**Review by alanking — APPROVED** [review]
Confirmed. I say # it.

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
