### PR TITLE
Fix redirection logic and add hostname configuration to run_tests.py (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
cherry-picked from work done for #5844

### CODE REVIEW

**Comment by trel** [comment]
please # if the tests are passing.

**Comment by alanking** [comment]
Confirmed that setup is not crashing, but will need some time to run tests

**Comment by alanking** [comment]
Found an issue with `itouch` through testing but everything else seems to be working. Running tests again

**Comment by alanking** [comment]
Tests are nearly finished running in topology from CSC, and passing. Squashed commit

**Comment by trel** [comment]
nice, yes, please # em up.

**Comment by alanking** [comment]
#'d

**Pull request merged**
