### PR TITLE
[#4862] Ensure data objects close in rsDataObjCopy (master)

### PR DESCRIPTION
**Pull request by alanking**
CI tests running

### CODE REVIEW

**Comment by trel** [comment]
so replacing the entire core.re with just this *did* work as expected?

**Comment by alanking** [comment]
Yep. Just needed to ensure that the environment did not define a default resource in order to trigger the desired behavior.

As a side bar, I'm making this a draft for now as the PREP will not be able to run this just yet. Hard-coded core.re in test.

**Comment by alanking** [comment]
CI tests passed. Also tested with PREP rule. Travis timed out, but it builds.

**Comment by trel** [comment]
looks good - please to #

**Pull request merged**
