### PR TITLE
[#6997] Stage-to-cache is performed by admin user (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #6997 
Reverts work done for #7038 
Cherry-picked from #7055 

Tests are running now

### CODE REVIEW

**Comment by korydraughn** [comment]
Did anything change in the cherry-pick or is it identical to the source?

**Comment by alanking** [comment]
Primary/Secondary are the new terms for the server host linked list, which differ from 4-2-stable. Headers have "irods/" prefixes in the include paths. No functional changes there.

The only other conflicts had to do with the fact that the roundrobin resource test suites still exist in 4-2-stable, but I just had to remove those sections.

Sorry, forgot to point those out.

**Comment by korydraughn** [comment]
Cool cool.

Will review once test results are reported.

**Comment by alanking** [comment]
Federation tests passed. `test_resource_types.Test_Resource_Compound` and `test_ibun` passed in topology for provider and consumer, which includes the new tests.

**Comment by trel** [comment]
Amazing.

**Review by korydraughn — APPROVED** [review]
Changes look good.

Pound and merge when ready.

**Pull request merged**
