### PR TITLE
[#7525] Remove dependency on "super" package (main)

### PR DESCRIPTION
**Pull request by korydraughn**
All unit tests pass for Ub20/22.

Preparing to run core tests for those platforms.

### CODE REVIEW

**Comment by korydraughn** [comment]
Oh right. If ub20/22 pass the core tests, I'll open an issue for that in the dev environment.

**Comment by korydraughn** [comment]
All core tests passed for ub20.

Running core tests for ub22.

**Review by SwooshyCueb — APPROVED** [review]

**Comment by korydraughn** [comment]
All core tests passed for ub22.

Squashing.

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
