### PR TITLE
Various test fixes (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #7718 
Addresses #7721 
Addresses #7725 

Confirmed that these tests now pass consistently when run with topology-on-consumer. Need to run full test suite for core tests,  topology-on-consumer, and topology-on-provider.

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
I don't see anything unusual. Let's get these merged.

Pound it.

**Comment by alanking** [comment]
Unit tests, core tests, and topology-on-provider are passing. Awaiting results for topology-on-consumer.

**Comment by alanking** [comment]
Saw two failures in topology-on-consumer which are not related to the changes here. See this comment for details: https://github.com/irods/irods/pull/7827#issuecomment-2189743026

Any objections to moving forward with these changes and addressing the failures separately either in the other PR or in https://github.com/irods/irods/issues/5593?

**Comment by korydraughn** [comment]
If the failures have nothing to do with these changes, let's move forward. We can address the failures in #5593.

**Comment by alanking** [comment]
Great. Added #s. Mergin

**Pull request merged**
