### PR TITLE
[#6887] allow igroupadmin mkuser to initialize the new user's password (main)

### PR DESCRIPTION
**Pull request by d-w-moore**
cherry-picked after applying review changes  and running full CI suite with all tests passing

### CODE REVIEW

**Comment by korydraughn** [comment]
Are you claiming that this PR is passing all the tests?

**Comment by d-w-moore** [comment]
> Are you claiming that this PR is passing all the tests?

Yes. Pre-cherry pick it passed on **4-2-stable**.  It now passes on **main**.

**Comment by alanking** [comment]
In the future, please link the PR and/or commit(s) from which the commits in this PR have been cherry-picked. It helps me a lot to to have the easy reference for greater context. Thanks!

Cherry-picked from #6889?

**Comment by d-w-moore** [comment]
!
> 
> Cherry-picked from #6889?
Yes

**Comment by d-w-moore** [comment]
And

**Comment by korydraughn** [comment]
Don't forget to run clang-format on the changes.

**Comment by d-w-moore** [comment]
> Don't forget to run clang-format on the changes.

Maybe i can get directions on procedure for how to do that

**Comment by d-w-moore** [comment]
Also i am aware I haven't made all the pull requests yet on the I commands side. Will do so and cross reference

**Comment by d-w-moore** [comment]
Corresponds to https://github.com/irods/irods_client_icommands/pull/357

**Review by alanking — COMMENTED** [review]
Yep, looks good. Please squash the clang-format commit into the "respect password field in igroupadmin mkuser USER PW" commit

**Review by alanking — APPROVED** [review]
Perfect. Please add #s

**Comment by d-w-moore** [comment]
done

**Pull request merged**
