### PR TITLE
[#7570] Declare server and dev package conflict with genquery2 package (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of #7570 

Adds the genquery2 plugin package to the "conflicts" delcarations for dev and server packages.

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look fine.

What does REPLACES and OBSOLETES do if the genquery2 package is installed prior to 4.3.2?

**Comment by korydraughn** [comment]
If someone has policy which depends on things in the genquery2 package, would this PR break their deployment?

**Comment by SwooshyCueb** [comment]
> What does REPLACES and OBSOLETES do if the genquery2 package is installed prior to 4.3.2?

The genquery2 packages will be uninstalled when the irods packages are updated to 4.3.2.

> If someone has policy which depends on things in the genquery2 package, would this PR break their deployment?

I have no idea.

Given that we never actually released the genquery2 plugin, I don't think it's of much concern.

**Comment by korydraughn** [comment]
> Given that we never actually released the genquery2 plugin, I don't think it's of much concern.

I see what you're saying, but I'm not all the way there yet. If an admin deploys policy/rules which use names only available in the genquery2 and we automatically uninstall the package on upgrade, their system could break when those rules are encountered. It feels wrong to uninstall the package without giving the admin a heads up.

Let's say the PR handled this via the CONFLICTS property ...
- What happens if the admin attempts to install the genquery2 package on a 4.3.2 server?
- What happens if genquery2 is installed on a 4.3.1 server and the admin upgrades to 4.3.2?

**Comment by SwooshyCueb** [comment]
> > Given that we never actually released the genquery2 plugin, I don't think it's of much concern.
> 
> I see what you're saying, but I'm not all the way there yet. If an admin deploys policy/rules which use names only available in the genquery2 and we automatically uninstall the package on upgrade, their system could break when those rules are encountered. It feels wrong to uninstall the package without giving the admin a heads up.

Makes sense

> Let's say the PR handled this via the CONFLICTS property ...
>     * What happens if the admin attempts to install the genquery2 package on a 4.3.2 server?

The package manager won't allow it.

>     * What happens if genquery2 is installed on a 4.3.1 server and the admin upgrades to 4.3.2?

My understanding is that it depends on the package manager frontend being used. Some may require that the user manually uninstall the genquery2 package first, and some will automatically make removing the genquery2 package part of the same transaction.

**Comment by korydraughn** [comment]
Ok. I'm leaning toward the packaging reporting a conflict unless there's a better way to do it. At the very least that gives the admin a chance to decide how they want to proceed.

Thoughts?

**Comment by SwooshyCueb** [comment]
I think I'm in agreement.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
I don't see the pound?

**Review by alanking — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d, for real this time

**Comment by alanking** [comment]
There we go. Mergin

**Pull request merged**
