### PR TITLE
[#3404] Refactor resource_manager::init_from_catalog (main)

### PR DESCRIPTION
**Pull request by alanking**
Rewrites init_from_catalog to use the irods::query iterator for fetching
information about existing resources and populating the resource
manager.

---

All tests passed

### CODE REVIEW

**Comment by alanking** [comment]
The main thing to focus on here is the fact that `process_init_results` was removed and a refactored implementation now exists in `init_from_catalog`.

**Comment by alanking** [comment]
Hmm... maybe not that one. Perhaps a similar type of issue could be opened for it, though. I don't think that should go into 4.3.0. Thoughts?

**Comment by trel** [comment]
No, not into 4.3.0... just thinking about how the data structure could be future-proofed for injection/update/overwrite later - and if that would influence this work.

Sounds like we're fine for now.

**Comment by trel** [comment]
looks good to me

**Review by korydraughn — APPROVED** [review]

**Comment by alanking** [comment]
#'d

**Pull request merged**
