### PR TITLE
Flatten zone report, calculate plugin checksums, add resource fields, and update schema (4-3 stable)

### PR DESCRIPTION
**Pull request by Nishant2022**

### CODE REVIEW

**Comment by Nishant2022** [comment]
Cherry pick from main.

**Comment by korydraughn** [comment]
Very good. Will look over it and give the approval soonish.

**Review by alanking — APPROVED** [review]
Cherry-picked from https://github.com/irods/irods/pull/7105

Looks very identical. Let's await one more approval

**Review by korydraughn — APPROVED** [review]
Please add the #'s and we'll get it merged.

**Comment by Nishant2022** [comment]
Added #'s

**Pull request merged**
