### PR TITLE
[#5863] Update mtime for creates/non-empty writes (master)

### PR DESCRIPTION
**Pull request by alanking**
Historically, the mtime for a replica was only updated if it was opened
for write (that is, it must have already existed) and bytes were written
during the operation. This changes the logic such that any operation
that results in a create or a bytes-writing open-for-write will update
the mtime for the target replica. This means that the mtime and create
time for a new replica may not be equal.

___
CI tests running

### CODE REVIEW

**Comment by trel** [comment]
looks good - please # when tests are happy

**Comment by alanking** [comment]
All tests passed except for `test_parallel_transfer_engine` unit test. Latest commit fixes this.

**Comment by trel** [comment]
awaiting kory eyeballs, then please #

**Comment by alanking** [comment]
#'d

**Pull request merged**
