### PR TITLE
Fixes for rc_switch_user unit tests (4-3-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Not yet tested.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Seems good. Noticed that the user removal in the at_scope_exit is slightly closer to the point of user creation (good) but differs from the commit in main (maybe fine?): https://github.com/irods/irods/commit/cbccd9fc5c19ebc8ed328dc5411f8c6465f56bcb Not sure if we wanted to reflect that change in main.

**Comment by korydraughn** [comment]
This is actually what should have been in main. Will tweak main to match this PR.

**Comment by korydraughn** [comment]
Unit tests pass.

**Review by alanking — APPROVED** [review]
Great. # it

**Comment by korydraughn** [comment]
Added pounds.

**Pull request merged**
