### PR TITLE
[#7687] Change log level severity of fallback log message: warn -> trace (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by alanking — APPROVED** [review]
\# when ready.

Is this at all related to https://github.com/irods/irods/pull/7672?

**Comment by trel** [comment]
i think that one is moot... should be closed with a 'reason' if so.

**Comment by korydraughn** [comment]
The other one is dead. I'm going to close it soon.

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
