### PR TITLE
[#4331] Bumpers for data_object_finalize (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
cherry-picked from work for #5594 

CI tests running

### CODE REVIEW

**Comment by alanking** [comment]
CI tests passed. #'d

**Comment by alanking** [comment]
Upon closer inspection, it seems that one test has failed in `test_iticket`. Need to investigate. Sorry about that.

**Comment by alanking** [comment]
CI tests passed. cherry-picked iticket test from master

**Comment by trel** [comment]
test looks good, please squash and # em.

**Comment by alanking** [comment]
#'d

**Pull request merged**
