### PR TITLE
Use proxy objects in rsDataObjClose + New replica/data_object features (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Cherry-picked from commits in #5191 

CI tests running.

### CODE REVIEW

**Comment by alanking** [comment]
Cherry-pick was not clean, apparently. Converting to draft

**Comment by alanking** [comment]
CI tests running

**Comment by alanking** [comment]
CI tests passed

**Comment by trel** [comment]
please to #

**Comment by alanking** [comment]
#'d

**Pull request merged**
