### PR TITLE
[#5575] Various fixes in rsDataObjPut (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Cherry-picked from changes in #5580 

CI tests running

### CODE REVIEW

**Comment by alanking** [comment]
The Codacy issue exists in master, so if I change it here, I would need to change it in master as well. Thoughts?

**Comment by trel** [comment]
sure, if you can clean it up here - you can make one more commit on master to do the same.   no worries.

**Comment by alanking** [comment]
CI tests passed without change. iput tests related to force putting to new resource passed with change, but I can run the whole suite again if desired.

**Comment by alanking** [comment]
#'d

**Pull request merged**
