### PR TITLE
[irods/irods_rule_engine_plugin_python#183] PREP tests: update references to global_vars (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
In service of irods/irods_rule_engine_plugin_python#183
Companion to irods/irods_rule_engine_plugin_python#185

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Looks solid so far. Are we planning to keep `testpaths.py`?

**Review by korydraughn — COMMENTED** [review]
I agree. Everything looks good.

What is testpaths.py used for? Is that a leftover?

**Comment by SwooshyCueb** [comment]
testpaths.py was not supposed to make it into the commit

**Comment by trel** [comment]
looks good to me

**Review by alanking — COMMENTED** [review]
\# it, I say

**Review by alanking — APPROVED** [review]
Whoops, didn't hit the button

**Comment by SwooshyCueb** [comment]
\#'d

**Review by korydraughn — APPROVED** [review]

**Pull request merged**
