### PR TITLE
[#5431] Added two microservices. (master)

### PR DESCRIPTION
**Pull request by trel**
They are called: msi_get_open_data_obj_l1desc_index and msi_get_file_descriptor_info.

This is to enable the resolution of an (open) data object path into its descriptor index,
and in reverse to return structured data (JSON) from the descriptor table by index.

this is a cherry pick of https://github.com/irods/irods/commit/7e8cc1f299b43d782584ca17726da3244e50f1e5

### CODE REVIEW

**Comment by alanking** [comment]
Looks like we need to add `IRODS_EXTERNALS_FULLPATH_FMT` to the `target_include_directories` and `target_link_libraries` in the `CMakeLists.txt` file so that the build system can find fmt. Curious that it didn't trip on 4-2-stable.

**Comment by ilarik** [comment]
Weird, I didn't even use `fmt` anywhere I think?

**Comment by ilarik** [comment]
Also, `nlohmann::json` I did use, and it seems that one doesn't get an explicit addition of an include directory in CMake, but also worked in `4-2-stable`.

**Comment by alanking** [comment]
Well, the error is coming out of spdlog (not used in 4-2-stable) which is being included in the microservice at a deep level:
```
 [ 91%] Building CXX object plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeFiles/msi_get_open_data_obj_l1desc_index.dir/libmsi_get_open_data_obj_l1desc_index.cpp.o
In file included from /home/runner/work/irods/irods/plugins/microservices/msi_get_open_data_obj_l1desc_index/libmsi_get_open_data_obj_l1desc_index.cpp:3:
In file included from /home/runner/work/irods/irods/server/re/include/irods_ms_plugin.hpp:15:
In file included from /home/runner/work/irods/irods/lib/core/include/irods_plugin_base.hpp:13:
In file included from /home/runner/work/irods/irods/server/re/include/irods_re_plugin.hpp:25:
In file included from /home/runner/work/irods/irods/server/core/include/irods_logger.hpp:21:
In file included from /opt/irods-externals/spdlog1.5.0-1/include/spdlog/spdlog.h:12:
In file included from /opt/irods-externals/spdlog1.5.0-1/include/spdlog/common.h:38:
/opt/irods-externals/spdlog1.5.0-1/include/spdlog/fmt/fmt.h:25:10: fatal error: 'fmt/core.h' file not found
#include <fmt/core.h>
         ^~~~~~~~~~~~
```
So that's a pretty easy fix, but still, a little odd.

**Comment by ilarik** [comment]
> Well, the error is coming out of spdlog (not used in 4-2-stable) which is being included in the microservice at a deep level:
> 
> ```
>  [ 91%] Building CXX object plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeFiles/msi_get_open_data_obj_l1desc_index.dir/libmsi_get_open_data_obj_l1desc_index.cpp.o
> In file included from /home/runner/work/irods/irods/plugins/microservices/msi_get_open_data_obj_l1desc_index/libmsi_get_open_data_obj_l1desc_index.cpp:3:
> In file included from /home/runner/work/irods/irods/server/re/include/irods_ms_plugin.hpp:15:
> In file included from /home/runner/work/irods/irods/lib/core/include/irods_plugin_base.hpp:13:
> In file included from /home/runner/work/irods/irods/server/re/include/irods_re_plugin.hpp:25:
> In file included from /home/runner/work/irods/irods/server/core/include/irods_logger.hpp:21:
> In file included from /opt/irods-externals/spdlog1.5.0-1/include/spdlog/spdlog.h:12:
> In file included from /opt/irods-externals/spdlog1.5.0-1/include/spdlog/common.h:38:
> /opt/irods-externals/spdlog1.5.0-1/include/spdlog/fmt/fmt.h:25:10: fatal error: 'fmt/core.h' file not found
> #include <fmt/core.h>
>          ^~~~~~~~~~~~
> ```
> 
> So that's a pretty easy fix, but still, a little odd.

Ok, makes sense. Should the JSON header path be added anyways to the `CMakeLists` in 4-2-stable? Even though it managed to find its way to `json.hpp` anyway due to some other header file being helpful and bringint it in probably...

**Comment by trel** [comment]
share a diff, and i'll get it repushed.

**Comment by alanking** [comment]
```diff
$ git diff
diff --git a/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt b/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
index 962578cda..eb0d03344 100644
--- a/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
+++ b/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
@@ -14,12 +14,14 @@ target_include_directories(${IRODS_PLUGIN_TARGET} PRIVATE ${CMAKE_BINARY_DIR}/li
                                                           ${CMAKE_SOURCE_DIR}/server/core/include
                                                           ${CMAKE_SOURCE_DIR}/server/icat/include
                                                           ${CMAKE_SOURCE_DIR}/server/re/include
-                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include)
+                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include
+                                                          ${IRODS_EXTERNALS_FULLPATH_FMT}/include)
 
 target_link_libraries(${IRODS_PLUGIN_TARGET} PRIVATE irods_server
                                                      irods_common
                                                      ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_filesystem.so
-                                                     ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_system.so)
+                                                     ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_system.so
+                                                     ${IRODS_EXTERNALS_FULLPATH_FMT}/lib/libfmt.so)
 
 install(TARGETS ${IRODS_PLUGIN_TARGET}
         LIBRARY DESTINATION ${IRODS_PLUGINS_DIRECTORY}/microservices
diff --git a/plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeLists.txt b/plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeLists.txt
index 1c4b196d1..2651ea52e 100644
--- a/plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeLists.txt
+++ b/plugins/microservices/msi_get_open_data_obj_l1desc_index/CMakeLists.txt
@@ -14,12 +14,14 @@ target_include_directories(${IRODS_PLUGIN_TARGET} PRIVATE ${CMAKE_BINARY_DIR}/li
                                                           ${CMAKE_SOURCE_DIR}/server/core/include
                                                           ${CMAKE_SOURCE_DIR}/server/icat/include
                                                           ${CMAKE_SOURCE_DIR}/server/re/include
-                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include)
+                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include
+                                                          ${IRODS_EXTERNALS_FULLPATH_FMT}/include)
 
 target_link_libraries(${IRODS_PLUGIN_TARGET} PRIVATE irods_server
                                                      irods_common
                                                      ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_filesystem.so
-                                                     ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_system.so)
+                                                     ${IRODS_EXTERNALS_FULLPATH_BOOST}/lib/libboost_system.so
+                                                     ${IRODS_EXTERNALS_FULLPATH_FMT}/lib/libfmt.so)
 
 install(TARGETS ${IRODS_PLUGIN_TARGET}
         LIBRARY DESTINATION ${IRODS_PLUGINS_DIRECTORY}/microservices
```

**Comment by ilarik** [comment]
For the required changes in `4-2-stable`
```
diff --git a/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt b/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
index 962578cda..d9592f1c1 100644
--- a/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
+++ b/plugins/microservices/msi_get_file_descriptor_info/CMakeLists.txt
@@ -14,7 +14,8 @@ target_include_directories(${IRODS_PLUGIN_TARGET} PRIVATE ${CMAKE_BINARY_DIR}/li
                                                           ${CMAKE_SOURCE_DIR}/server/core/include
                                                           ${CMAKE_SOURCE_DIR}/server/icat/include
                                                           ${CMAKE_SOURCE_DIR}/server/re/include
-                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include)
+                                                          ${IRODS_EXTERNALS_FULLPATH_BOOST}/include
+                                                          ${IRODS_EXTERNALS_FULLPATH_JSON}/include)
 
 target_link_libraries(${IRODS_PLUGIN_TARGET} PRIVATE irods_server
                                                      irods_common
```

**Pull request merged**
