### PR TITLE
[#5081] Add test class for interactive imeta (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Companion pull request for irods/irods_client_icommands#163

A few tests for interactive `imeta`

Addresses #5081

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good to me.

Without deeply evaluating, it looks like this could possibly benefit from a utility in our testing suite called `delayAssert` which repeatedly tries an assertion up to a certain number or if it passes. But this is fine how it is, just wanted to make mention of that.

Also, per commit message, should we create an issue for REPL testing?

**Comment by SwooshyCueb** [comment]
> Also, per commit message, should we create an issue for REPL testing?

Yeah, I think that might be a good idea

**Comment by trel** [comment]
Agreed, please create an issue for that - and tweak the commit message to leave out the suggestion.

If tests are passing, please # it.

**Comment by SwooshyCueb** [comment]
All tests passed except the one that doesn't. #s added

**Pull request merged**
