### PR TITLE
[#6754] Deprecated member variables of the l1desc data type (4-3-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cherry-picked from #6797.

Will run unit tests before adding the pound.

### CODE REVIEW

**Comment by korydraughn** [comment]
All unit tests passed.

Adding #

**Comment by korydraughn** [comment]
#'d

**Comment by korydraughn** [comment]
Let me fix the clang-format/tidy before merging this.

**Comment by korydraughn** [comment]
Ready to be merged.

**Comment by korydraughn** [comment]
Codacy is not enabled for the 4-3-stable branch.

We need to enable it or remove it entirely. Let's enable it until we can build github actions to replace it.

**Comment by trel** [comment]
I've enabled it - we should see codacy reports now for 4-3-stable PRs.

**Review by alanking — APPROVED** [review]

**Pull request merged**
