### PR TITLE
[#7104] Honor logical locking in rsDataObjTruncate (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #7104...?

I'm opening the PR for eyeballs. The new unit test fails appropriately before the C++ changes and passes appropriately after the C++ changes. Still need to run all the other tests.

I have a few questions that we can discuss here or offline:
1. As has been discussed elsewhere, the expectation was to implement a new API endpoint. I figured it would be just as well to modify the existing endpoint. Do we want to introduce a new API over modifying the existing one? Why?
2. If we make a new API, should we deprecate the existing one?
3. Do we want to expand testing for truncate as part of this effort? Currently, there are no tests for this API.

### CODE REVIEW

**Comment by korydraughn** [comment]
My first thought on this is ... should we make this an API plugin (that lives in its own repo)?

The reason for that thought is due to NFSRODS. It's next release is very close, but depends on whether we want to add support for truncate. I think it would be a nice feature to have.

Think on it and we can discuss tomorrow.

Will think about your questions in the meantime.

**Comment by trel** [comment]
your 4. seems... reasonable?   any weird side effects we can predict?   it's just a replica, we do stuff to it, we close it... and then the other replicas may be informed/updated as well to match.

**Comment by alanking** [comment]
When an object is locked, it means one of the replicas is intermediate with the assumption that the other replicas are at rest. The API currently truncates *all replicas*. Saying "yes" to 4 may prove tricky. There's currently no support for targeting a specific replica to truncate using this API (as far as I can tell). This definitely warrants a discussion about The Future.

**Comment by korydraughn** [comment]
Shouldn't need the replica access token in 99% of cases. I can't think of a reason why someone would need that, but you never know.

(4) sounds fine. It kind of removes the need for logical locking in the truncate implementation. If clients are required to open a replica, then on success, the locking has already happened.

**Comment by alanking** [comment]
After discussing things, I think I'm going to close this PR. I'll leave the branch around in my repo and will post more updates in #7104.

**Pull request closed without merging**
