### PR TITLE
[#6656] Add symlink restriction to msiTarFileExtract Doxygen (main)

### PR DESCRIPTION
**Pull request by alanking**
In service of #6656 

Related to but not necessarily a companion PR for https://github.com/irods/irods_client_icommands/pull/465

### CODE REVIEW

**Comment by trel** [comment]
i like it.

**Comment by alanking** [comment]
Ignoring clang-format on this one. I didn't touch the lines it's complaining about.

**Comment by alanking** [comment]
#'d, but, since it's Doxygen, figured I would poke @korydraughn before merging, just in case.

**Review by korydraughn — APPROVED** [review]
Merge it.

**Pull request merged**
