### PR TITLE
[5392] added additional hash algorithms

### PR DESCRIPTION
**Pull request by JustinKyleJames**
see [irods/irods_client_globus_connector#9]

sha512
sha1
adler32

### CODE REVIEW

**Comment by trel** [comment]
@korydraughn anything else here?

if not, justin, please squash and #.

**Comment by JustinKyleJames** [comment]
Collapsed into one commit.

**Comment by trel** [comment]
please # it

**Comment by JustinKyleJames** [comment]
> please # it

done

**Pull request merged**
