### PR TITLE
[3461] change default server SSL policy to CS_NEG_REFUSE (master)

### PR DESCRIPTION
**Pull request by trel**
needs a run through CI...

probably missed a couple places in the tests that need to be tweaked for the new default.

### CODE REVIEW

**Comment by trel** [comment]
need to change the python core.py.template to remain consistent as well

**Comment by trel** [comment]
#'d here and https://github.com/irods/irods_rule_engine_plugin_python/pull/117

oh, also need to do the default cpp...

**Review by korydraughn — APPROVED** [review]

**Comment by alanking** [comment]
I have observed some failures in the tests when I cherry-picked this change into a local branch, so I will need to examine this more carefully...

**Comment by alanking** [comment]
Tried again and the tests passed. I think we may have an intermittently failing test which we should watch for (`test_iadmin.Test_Iadmin.test_host_access_control`). It is not related to this change as far as I can tell.

**Review by alanking — APPROVED** [review]

**Pull request merged**
