### PR TITLE
[#3602] Timestamps in python log output are now displayed in UTC time (main)

### PR DESCRIPTION
**Pull request by korydraughn**
I'm not sure we actually need this, but we can discuss how important/useful this is here.

This needs to be ran through the test suite.

### CODE REVIEW

**Comment by SwooshyCueb** [comment]
IMHO if we want to be Normal and Boring:tm: we should use whatever timezone the system is configured for. 
I could see an argument for explicitly using UTC if we're printing raw seconds-since-epoch timestamps or something like that, but it doesn't look like that's what we're doing.

**Comment by trel** [comment]
We do want to consider that multi-timezone iRODS Zones could begin to more easily consolidate their logging via remote rsyslogd... does that suggest we should stick to all-UTC for sanity?   Looks like rsyslogd knows/understands timezones if they're part of the timestamp correctly...

**Comment by korydraughn** [comment]
Moving to UTC for all log file output is likely a good idea. Things are inconsistent today (e.g. compare timestamps of irods.log and control_log.txt). This change helps to improve on that.

I just now noticed that irods.log presents milliseconds and does not include the trailing `Z` while the python log output does not include milliseconds. I'll take care of that soon.

**Comment by korydraughn** [comment]
I've updated both the python logger and server logger to use the same format. The change does make it easier to see the order of things across different log files.

**Comment by d-w-moore** [comment]
The  Python bit looks good . Tried them out myself, it  aligns very well and time & other output seem all correct.  The C++ change seems correct, far as I can tell.

**Review by d-w-moore — APPROVED** [review]

**Comment by korydraughn** [comment]
Excellent!

**Review by alanking — COMMENTED** [review]
I'm good with it if everyone else is good with it. :)

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
