### PR TITLE
[#6231] Server correctly cleans up proc files (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Very nice. Would it be worth adding a test for this?

**Comment by korydraughn** [comment]
Will do

**Comment by korydraughn** [comment]
Added test.

Any last thoughts before I add the #'s?

**Review by alanking — APPROVED** [review]

**Comment by trel** [comment]
looks good by inspection.

**Comment by korydraughn** [comment]
added #

**Comment by alanking** [comment]
Merging on green

**Pull request merged**
