### PR TITLE
[#6670] Add where clause in delete from R_ObjectId_seq_tbl (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cherry-picked #6632

### CODE REVIEW

**Comment by trel** [comment]
this one has more words and no #...

**Comment by korydraughn** [comment]
> this one has more words and no #...

Other than the missing #, the commit messages appear identical. Can you point out what I'm missing?

**Comment by trel** [comment]
i thought one of the three PRs was missing the extra commit message - but, no... all three are identical.

carry on!

**Review by alanking — APPROVED** [review]
Please add # if tests are passing

**Comment by korydraughn** [comment]
This PR failed against Ubuntu 18 / MySQL 5.7.

The failures may have something to do with MySQL 5.7.

Given that 4.2.12 is likely the final release of the 4.2 series, it may be better to keep this as a 4.3 only change.

**Comment by trel** [comment]
The 5.7 series was first released in 2013.   It might just not understand this syntax.

Can you share the failure you see in the test(s)?

**Comment by korydraughn** [comment]
I don't have the output. The tests were stuck. Jumping into the container didn't' provide any additional information either.

I'll try running the tests again. 4.3.0/MySQL 8 did not have this problem.

**Comment by trel** [comment]
Got it.

Ideally, we put it into 4-2-stable, but with a known minimum MySQL version.  Double bonus points for links / understanding of why that's the minimum version.

**Comment by korydraughn** [comment]
All unit tests passed against Ubuntu 18 / MySQL 5.7.

Running core tests again.

**Comment by korydraughn** [comment]
Tests failed early. Below is the output.

Notice the first failure is for test_imv.py.
```
2022-11-09 08:57:00,689 - [ubuntu-1804-mysql-57_irods-catalog-provider_1]: running test [test_all_rules]
2022-11-09 08:57:00,690 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: running test [test_catalog]
2022-11-09 08:57:00,692 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_collection_mtime]
2022-11-09 08:57:00,693 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_control_plane]
2022-11-09 08:57:32,047 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: test passed [[  31.3550]s] [test_catalog]
2022-11-09 08:57:32,047 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: running test [test_delay_queue]
2022-11-09 08:57:32,724 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test passed [[  32.0278]s] [test_collection_mtime]
2022-11-09 08:57:32,724 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_dynamic_peps]
2022-11-09 08:57:49,145 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test passed [[  16.4210]s] [test_dynamic_peps]
2022-11-09 08:57:49,146 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_iadmin]
2022-11-09 09:01:20,591 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[ 259.8947]s] [test_control_plane]
2022-11-09 09:01:20,591 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ibun]
2022-11-09 09:03:09,496 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[ 108.9041]s] [test_ibun]
2022-11-09 09:03:09,496 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_icd]
2022-11-09 09:03:24,986 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  15.4902]s] [test_icd]
2022-11-09 09:03:24,987 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ichksum]
2022-11-09 09:03:58,881 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: test passed [[ 386.8329]s] [test_delay_queue]
2022-11-09 09:03:58,881 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: running test [test_ichmod]
2022-11-09 09:04:11,330 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: test passed [[  12.4484]s] [test_ichmod]
2022-11-09 09:04:11,330 - [ubuntu-1804-mysql-57_irods-catalog-provider_2]: running test [test_icommands_file_operations]
2022-11-09 09:07:00,157 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[ 215.1697]s] [test_ichksum]
2022-11-09 09:07:00,157 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_icp]
2022-11-09 09:11:27,309 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[ 267.1517]s] [test_icp]
2022-11-09 09:11:27,309 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_iexit]
2022-11-09 09:11:28,199 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[   0.8899]s] [test_iexit]
2022-11-09 09:11:28,199 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ifsck]
2022-11-09 09:11:40,489 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  12.2890]s] [test_ifsck]
2022-11-09 09:11:40,489 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_igroupadmin]
2022-11-09 09:11:54,048 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  13.5591]s] [test_igroupadmin]
2022-11-09 09:11:54,049 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ihelp]
2022-11-09 09:11:55,942 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[   1.8937]s] [test_ihelp]
2022-11-09 09:11:55,943 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ilocate]
2022-11-09 09:12:07,738 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  11.7947]s] [test_ilocate]
2022-11-09 09:12:07,738 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ils]
2022-11-09 09:13:13,559 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  65.8208]s] [test_ils]
2022-11-09 09:13:13,560 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_ilsresc]
2022-11-09 09:13:32,715 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  19.1550]s] [test_ilsresc]
2022-11-09 09:13:32,715 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_imeta_admin_mode]
2022-11-09 09:14:02,468 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  29.7528]s] [test_imeta_admin_mode]
2022-11-09 09:14:02,469 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_imeta_error_handling]
2022-11-09 09:14:20,889 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  18.4202]s] [test_imeta_error_handling]
2022-11-09 09:14:20,890 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_imeta_help]
2022-11-09 09:14:28,885 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[   7.9955]s] [test_imeta_help]
2022-11-09 09:14:28,886 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_imeta_interactive]
2022-11-09 09:14:53,286 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test passed [[  24.3996]s] [test_imeta_interactive]
2022-11-09 09:14:53,286 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_imeta_set]
2022-11-09 09:15:45,670 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test passed [[1076.5231]s] [test_iadmin]
2022-11-09 09:15:45,670 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_imkdir]
2022-11-09 09:16:06,048 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test passed [[  20.3782]s] [test_imkdir]
2022-11-09 09:16:06,049 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_imv]
2022-11-09 09:22:53,462 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test failed [[ 407.4135]s] [test_imv]
2022-11-09 09:22:53,463 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_ipasswd]
2022-11-09 09:33:14,076 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: test failed [[1100.7895]s] [test_imeta_set]
2022-11-09 09:33:14,076 - [ubuntu-1804-mysql-57_irods-catalog-provider_4]: running test [test_iphymv]
2022-11-09 09:36:14,912 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test failed [[ 801.4491]s] [test_ipasswd]
2022-11-09 09:36:14,913 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_iput]
2022-11-09 10:02:57,125 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: test failed [[1602.2121]s] [test_iput]
2022-11-09 10:02:57,126 - [ubuntu-1804-mysql-57_irods-catalog-provider_3]: running test [test_iput_options]
```
Below is the report for test_imv.py. Something didn't clean up properly.
```
<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="irods.test.test_imv.Test_Imv-20221109141606" tests="3" time="406.970">
        <testcase classname="irods.test.test_imv.Test_Imv" name="test_imv_boost_any_cast_exception_on_rename__issue_4301" time="4.123"/>
        <testcase classname="irods.test.test_imv.Test_Imv" name="test_imv_prints_error_on_non_existent_collection__issue_4414" time="202.584">
                <error message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_imv.py", line 23, in tearDown
    super(Test_Imv, self).tearDown()
  File "/var/lib/irods/scripts/irods/test/session.py", line 82, in tearDown
    with make_session_for_existing_admin() as admin_session:
  File "/var/lib/irods/scripts/irods/test/session.py", line 37, in make_session_for_existing_admin
    return IrodsSession(env_dict, test.settings.PREEXISTING_ADMIN_PASSWORD, False)
  File "/var/lib/irods/scripts/irods/test/session.py", line 103, in __init__
    self.assert_icommand(['iinit', self._password])
  File "/var/lib/irods/scripts/irods/test/session.py", line 159, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
]]>             </error>
        </testcase>
        <testcase classname="irods.test.test_imv.Test_Imv" name="test_imv_with_apostrophe_logical_path__issue_5759" time="200.263">
                <error message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/var/lib/irods/scripts/irods/test/test_imv.py", line 18, in setUp
    super(Test_Imv, self).setUp()
  File "/var/lib/irods/scripts/irods/test/session.py", line 74, in setUp
    with make_session_for_existing_admin() as admin_session:
  File "/var/lib/irods/scripts/irods/test/session.py", line 37, in make_session_for_existing_admin
    return IrodsSession(env_dict, test.settings.PREEXISTING_ADMIN_PASSWORD, False)
  File "/var/lib/irods/scripts/irods/test/session.py", line 103, in __init__
    self.assert_icommand(['iinit', self._password])
  File "/var/lib/irods/scripts/irods/test/session.py", line 159, in assert_icommand
    return assert_command(*args, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 77, in assert_command
    return _assert_helper(*args, should_fail=False, **kwargs)
  File "/var/lib/irods/scripts/irods/test/command.py", line 105, in _assert_helper
    assert result
AssertionError
]]>             </error>
        </testcase>
        <system-out>
```

This PR breaks 4-2-stable.

I'll add support for 4-2-stable / MySQL 8 to the testing environment and see how it behaves.

**Comment by korydraughn** [comment]
Unless there's a way to get around https://github.com/irods/irods_testing_environment/pull/131#issuecomment-1309492118, I don't feel this PR will and in 4-2-stable.

And that's okay because 4-2-stable is being phased out by 4.3.

**Comment by alanking** [comment]
@peterverraedt - Do you have any thoughts about this change going into 4.2.12? What if we made this change a 4.3.x-only change?

**Comment by peterverraedt** [comment]
I'm fine with a 4.3.x-only bugfix - it is easy to patch running 4.2 zones if needed.

**Comment by korydraughn** [comment]
Sounds good. We'll close this PR and focus on getting the upgrade path for MySQL handled.

Thanks.

**Pull request closed without merging**
