### PR TITLE
[#4311] return error for string literals > 1021 characters

### PR DESCRIPTION
**Pull request by d-w-moore**
The irods #4311 (string length overflow/ non-null-termination bug originally reported in [iRODS Chat](https://groups.google.com/d/msg/irod-chat/NTgPmfzRW0M/QB6OsdOoBAAJ) ) fix ported from 4-2-stable.

### CODE REVIEW

**Comment by trel** [comment]
confirming this passed CI?

**Comment by d-w-moore** [comment]
I took the #4311 commit out, and it still fails.  Will add this to comment section!


________________________________

**Comment by d-w-moore** [comment]
This doesn't yet pass in CI, however master also fails CI absent this commit

**Comment by d-w-moore** [comment]
Recommend this patch for immediate merging in master, as reasons for failure in CI with (also without) this commit are unrelated to the issue at hand. It has passed in iRODS 4-2-stable, and at the bench in master.

**Pull request merged**
