### PR TITLE
Fix redirection logic and add hostname configuration to run_tests.py (master)

### PR DESCRIPTION
**Pull request by alanking**
Setting up CSCs now works and have confirmed that no disconnection error messages appear in the CSP log when a CSC-connected agent goes away (meaning, the connections are now cleaning up appropriately).

### CODE REVIEW

**Comment by trel** [comment]
green, and looks good to me - please # if happy.

**Review by korydraughn — APPROVED** [review]
Very nice!

If you have knowledge around how the C APIs and structures work in regards to `ServerHostHead`, `svrToSvrConnect`, etc., please add documentation for them. You can add that in a separate PR if you prefer.

Just don't want to lose what you've learned.

**Comment by alanking** [comment]
Sure, I'll add some notes to the declarations.

**Comment by trel** [comment]
looks good - please merge/meld the last commit into the other two?   or add ye olde 858?

**Comment by trel** [comment]
oh, you checked Doxygen rendered these well?

**Comment by alanking** [comment]
Have not tried yet, will try soon

**Comment by alanking** [comment]
Confirmed that the Doxygen renders properly. #'d

**Pull request merged**
