### PR TITLE
[#6334] Python2-syntax compat. for RPM byte-compile on centos7

### PR DESCRIPTION
**Pull request by d-w-moore**
lack of Python2 compatibility (for metaclass and print function) were causing RPM bytecompiling to trip over some test related scripts.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
@SwooshyCueb, does this seem okay to go in for you until your work on this front makes it? Or should we hold off til then? This seems fine to put in for the time being, IMO, but wanted to check in.

**Comment by d-w-moore** [comment]
Hopefully I can change the commit message without nulling the approval status? : )

**Comment by korydraughn** [comment]
It's fine. We can always approve it again.

**Comment by SwooshyCueb** [comment]
Yeah nothing I'm doing is changing the .py files themselves so should be fine to merge this now.
Was hoping to have my PRs in yesterday but I ran into some trouble while testing.

**Review by alanking — APPROVED** [review]
Let's # it

**Comment by trel** [comment]
why does the second commit refer to the prep repo?   don't we have a py3 issue in irods/irods?

**Comment by alanking** [comment]
The modified tests in the second commit are PREP-only:
```python
@unittest.skipUnless(plugin_name == 'irods_rule_engine_plugin-python', 'only applicable for python REP')
```

**Comment by trel** [comment]
gotcha.

**Comment by d-w-moore** [comment]
Still bandying it about, trying to get a solution to `test_acPostProcForPut_replicate_to_multiple_resources`, which is just a generally misbehaving test on both NREP and PREP under 4.3.0.

Then we can # this and the other PRs now queued up for PREP/4.3.0 + Python3 + iRODS testing.

**Comment by d-w-moore** [comment]
Ah, ok . Scratch the NREP part of that statement.  I just retested with a clean install and NREP behavior is good  on` test_acPostProcForPut_replicate_to_multiple_resources` (it wasn't, last night.) 

Now to track down the real problem, why PREP can't replicate to an empty resource without thinking it's "full"....

**Comment by alanking** [comment]
The PREP test issue(s) seem to be more related to the other PR - if I'm understanding correctly - so I think this is probably good to go. Make sure to try it again after rebasing to make sure things are still working.

**Comment by d-w-moore** [comment]
#'d

**Pull request merged**
