### PR TITLE
[4063] Ensure AVUs set properly (4-3-stable)

### PR DESCRIPTION
**Pull request by MartinFlores751**
Cherry-pick of #6853.

Ran core & cpp tests, all passed.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks super the same. Good. Please # it

**Comment by MartinFlores751** [comment]
Cherry-picked the clang-format before squashing in main, so it should be the same.

**Review by alanking — COMMENTED** [review]
Sorry about that clang-format mishap. Please squash and leave off the #s.

**Review by korydraughn — APPROVED** [review]
Pound it up and we'll get it merged.

**Pull request merged**
