### PR TITLE
[#6511] UseLibCXX: Fix LINK_LANGUAGE version guard (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Takes care of #6511 for main.
Will be cherry-picked into 4-3-stable if github actions builds succeed.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Nice

@korydraughn's and/or @trel ?

**Review by korydraughn — APPROVED** [review]
@SwooshyCueb Do you know if merging this PR will close the issue or not?

Given that this fix applies to multiple branches, if merging this PR causes the issue to be closed before the other PRs are merged, then we need to avoid using the auto-close features for issues and PRs.

Is there a way to make Github understand that multiple PRs need to be merged before closing the issue?

**Comment by SwooshyCueb** [comment]
Yes, merging this PR will close the issue. I'm not aware of a way to link multiple PRs to a single issue. But given that I have PRs in for all three relevant branches, I think it's a non-issue in this particular case, provided all three are merged together.

**Comment by korydraughn** [comment]
Ok. Let's remove the use of "Fixes" from the PRs so none of them close the issue. That let's gives us a chance to check the boxes and have the closing of the issue be the final step.

At this point, removal of "Fixes" from the comments may be pointless, but we'll at least see out what github does when attempting to unlink an issue.

**Comment by trel** [comment]
Yeah, we'd just keep them tight in time... or just re-open.    Or... of course, don't use the magic words that GitHub knows...

**Comment by SwooshyCueb** [comment]
PR unlinked from the issue.

Found some more information on PR-issue linking: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

Unless I missed it, it does not say what the behavior is when multiple PRs are linked to a single issue.
Regardless, I do not have permission to manually link or un-link issues in the way described in this article.

**Comment by alanking** [comment]
It appears that none of the PRs is linked to the issue now, thanks to changing the wording in the original message. I'll merge shortly barring any objections

**Pull request merged**
