### PR TITLE
[#4951] Update CMake distribution check to use lsb_release rather than deprecated python

### LINKED ISSUE #4951: platform.linux_distribution is deprecated in python 3.7 and removed in 3.8
### iRODS Version, OS and Version
4.2.7

### What did you try to do?
CMakeLists.txt contains a reference to platform.linux_distribution which no longer exists this causes an error when running cmake.

### Expected behavior
IRODS uses a non-deprecated method to check linux_distribution.

### Observed behavior (including steps to reproduce, if applicable)

```
-- Found OpenSSL: $PREFIX/lib/libcrypto.so (found version "1.0.2o") 
-- Found pam: /usr/lib/x86_64-linux-gnu/libpam.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
CMake Error at CMakeLists.txt:93 (message):
  Linux platform name detection failed

  1


-- Configuring incomplete, errors occurred!
See also "$SRC_DIR/build/CMakeFiles/CMakeOutput.log".
See also "$SRC_DIR/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/home/gsinstall/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 474, in main
    execute(sys.argv[1:])
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
    verify=args.verify, variants=args.variants)
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2863, in build_tree
    notest=notest,
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1994, in build
    cwd=src_dir, stats=build_stats)
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/gsinstall/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 384, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/gsinstall/miniconda/conda-bld/irods_1590711835372/work/conda_build.sh']' returned non-zero exit status 1
```

### PR DESCRIPTION
**Pull request by mp15**
Existing call to python using platform.linux_distribution was deprecated in 3.7 and removed in 3.8.
Replace with call to lsb_release.
Fixes #4951

### CODE REVIEW

**Comment by mp15** [comment]
Note that Tarvis failure is due to exceeding time requirements.

**Comment by kript** [comment]
PSA: @mp15 is part of Sanger, so can we have the 'consortium member` tag for this contributions!

**Comment by trel** [comment]
naturally!

**Comment by SwooshyCueb** [comment]
I've got Python 3.8 on my personal machine, so I've run into this a couple times. What's holding up this pull request?

**Comment by trel** [comment]
Nothing - we can do this in master.   We just need to confirm it doesn't break the Python2-as-default supported distributions.

**Comment by trel** [comment]
CentOS7 needs the `redhat-lsb-core` package

Ubuntu needs the `lsb-release` package

**Comment by SwooshyCueb** [comment]
I have just discovered that we are already using `lsb_release` in one location here:
https://github.com/irods/irods/blob/a818fe2fe7ae2092a6ddbef2b4dbad83aa907e87/CMakeLists.txt#L153

**Comment by trel** [comment]
Good find... merged 4.5 years ago...

https://github.com/irods/irods/blame/9eb6c23df45cdedff8ee9c3af71a65d304635037/CMakeLists.txt#L128

And shipped in 4.2.0...  was part of https://github.com/irods/irods/issues/2656

**Comment by SwooshyCueb** [comment]
Relatedly, we should probably be using `lsb_release` in `packaging/find_os.sh` and `packaging/find_os_version.sh` as well

**Comment by alanking** [comment]
This seems to be superseded by https://github.com/irods/irods/commit/9215fb2204df1050b2a97f602ba839ea9c36d3c5

Can we close this, @SwooshyCueb?

**Comment by SwooshyCueb** [comment]
Yeah. Eventually we'll be moving away from platform detection in CMake altogether. Let's close this.

**Pull request closed without merging**
