### PR TITLE
[#5731] Renamed header file and added to C API test (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
This PR renames **checksum.hpp** to **checksum.h**.

This change will break any code that included the old header name.

### CODE REVIEW

**Comment by trel** [comment]
build failed

**Comment by korydraughn** [comment]
I just built this from scratch. Is the github actions build step caching any artifacts?

**Comment by trel** [comment]
seems... unlikely?   all i see is this...

https://github.com/irods/irods/pull/5732/checks?check_run_id=3008935508

**Comment by korydraughn** [comment]
I forgot to add the renamed header to the commit. This should successfully build now.

**Comment by trel** [comment]
cool, looks good, please # once green.

**Comment by korydraughn** [comment]
passed CI

added #

**Pull request merged**
