### PR TITLE
[XXXXX] Move Test_Resource_Replication_With_Retry to timing_test suite (master)

### PR DESCRIPTION
**Pull request by alanking**
Test class no longer derives from ResourceBase, resulting in fewer tests required to be implemented. Tests pass at the bench.

### CODE REVIEW

**Comment by alanking** [comment]
CI tests passed, just trying to make Codacy happy

**Comment by alanking** [comment]
I used python2.7 modules as an example for the docstrings and am in conformance with those. I can keep trying with PEP257 but at this point I do not know what it wants me to do.

**Comment by trel** [comment]
squash and forget.

**Comment by alanking** [comment]
Done. Using 858 as this is a test cleanup effort.

**Pull request merged**
