### PR TITLE
[#7590] irods_setup: Prevent local resource creation when user says no (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #7590 

Tested manually on Debian 12.

### CODE REVIEW

**Comment by trel** [comment]
seems excellent

**Review by korydraughn — APPROVED** [review]
Seems good to me.

You've reproduced the issue and implemented a fix for it. Happy to get this merged, but feel free to wait for confirmation from the user that the change satisfies their needs.

**Comment by alanking** [comment]
I will give it a day and then #.

**Comment by korydraughn** [comment]
Sounds good.

**Comment by alanking** [comment]
User has confirmed that this fixes the issue, so... #'d, and merging.

**Pull request merged**
