### PR TITLE
[6716] Put base64 methods in irods namespace (4-3-stable)

### PR DESCRIPTION
**Pull request by JustinKyleJames**
This is simply a cherry-pick of 6716 for 4-3-stable.

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
@JustinKyleJames - Were there any changes which occurred in #6736 which are not reflected here? I ran `git diff` against main with this branch and they look identical, but please to confirm.

**Comment by JustinKyleJames** [comment]
> @JustinKyleJames - Were there any changes which occurred in #6736 which are not reflected here? I ran `git diff` against main with this branch and they look identical, but please to confirm.

No, they are identical.

**Review by alanking — DISMISSED** [review]
Sweet. # it up

**Comment by JustinKyleJames** [comment]
Pounded

**Review by alanking — APPROVED** [review]

**Pull request merged**
