### PR TITLE
[6743] nre.reLib1.cpp:extractVarNames: do not write past the end of varNames (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses 6743 for main

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Please apply clang-format changes and I think this is good to go.

Just asking... probably not worth a test, right?

**Comment by korydraughn** [comment]
Because we're touching the rule language, let's run the change through the unit tests and core tests.

You can never be too sure what will happen once we start touching things down there.

**Comment by alanking** [comment]
Right, sorry, I meant to say a *new* test. Yes, we should run this through the test suite(s) before merging. :)

**Comment by SwooshyCueb** [comment]
I'm not currently set up to run the test suite. Will wait for results from someone else

**Comment by korydraughn** [comment]
Let's go ahead and get the testing environment set up so you can run the tests.

You can use the test VMs if you don't want to run the tests locally. I don't think anyone is using them at the moment.

**Comment by SwooshyCueb** [comment]
Yes, I'll need to use the VMs until the new workstation comes in. I'll poke you about it tomorrow.

**Comment by SwooshyCueb** [comment]
Ran core and unit tests, all passed.

**Review by korydraughn — APPROVED** [review]
Please add the pound.

**Review by alanking — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
