### PR TITLE
[5323] Adding FILE_PATH_KW in finalize for put copy

### PR DESCRIPTION
**Pull request by JustinKyleJames**

### CODE REVIEW

**Comment by trel** [comment]
seems good - this is tested in the s3 plugin suite?

**Comment by JustinKyleJames** [comment]
> seems good - this is tested in the s3 plugin suite?

Yes and I ran the various resource tests as well.

**Comment by trel** [comment]
please to #

**Comment by JustinKyleJames** [comment]
> please to #

Done

**Pull request merged**
