### PR TITLE
[#6300] Move namelinks to development package

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Fixes 6300

This moves files (symlinks) from one package to another and therefore requires the declaration of a "replaces" package relationship for dpkg. Upgrades from earlier *releases* should work fine, but upgrades from earlier development versions of 4.3.0 will require manual intervention.

Before I feel comfortable \#'ing this, I'd like someone with a working docker development environment to make sure packages built from this PR can install on top of 4.2.* packages. Mine is still in a bit of a weird state while I work on irods/irods_development_environment#44.

### CODE REVIEW

**Comment by trel** [comment]
commit message ... "pacakge" -> "package"

**Comment by trel** [comment]
might need the RPM equivalent as well

**Comment by korydraughn** [comment]
I've verified that the upgrade from 4.2.11 to this PR works.

That is, I was able to do the following:
1. install the packages
2. run `apt-get install -fy`
3. start the server
4. then do a put

@SwooshyCueb Is there anything else we need to test for this PR?

**Comment by SwooshyCueb** [comment]
@korydraughn should also be tested with an rpm-based distro as well, for good measure

**Comment by korydraughn** [comment]
Ok. Will do.

**Comment by korydraughn** [comment]
The development environment builder for CentOS 7 didn't produce an irods-server package.

Hit this again: https://github.com/irods/irods_development_environment/issues/34

Can't verify CentOS 7 until this is resolved.

Build output:
```bash
[1001/1002] Run CPack packaging tool...                                                                                                                                                                                                                                                                                                                                                      
CPack: Create package using RPM                                                                                                                                                                                                                                                                                                                                                              
CPack: Install projects                                                                                                                                                                                                                                                                                                                                                                      
CPack: - Install project: irods []                                                                                                                                                                                                                                                                                                                                                           
CPack: -   Install component: irods-database-plugin-mysql                                                                                                                                                                                                                                                                                                                                    
CPack: -   Install component: irods-database-plugin-oracle                                                                                                                                                                                                                                                                                                                                   
CPack: -   Install component: irods-database-plugin-postgres                                                                                                                                                                                                                                                                                                                                 
CPack: -   Install component: irods-dev                                                                                                                                                                                                                                                                                                                                                      
CPack: -   Install component: irods-runtime                                                                                                                                                                                                                                                                                                                                                  
CPack: -   Install component: irods-server                                                                                                                                                                                                                                                                                                                                                   
CPack: Create package                                                                                                                                                                                                                                                                                                                                                                        
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-mysql.spec                                                                                                                                                                                                                                                                        
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-oracle.spec                                                                                                                                                                                                                                                                       
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-postgres.spec                                                                                                                                                                                                                                                                     
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-devel.spec                                                                                                                                                                                                                                                                                        
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-runtime.spec                                                                                                                                                                                                                                                                                      
CMake Warning (dev) at /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1116 (message):                                                                                                                                                                                                                                                             
  CPackRPM:Warning: SUGGESTS not supported in provided rpmbuild.  Tag will                                                                                                                                                                                                                                                                                                                   
  not be used.                                                                                                                                                                                                                                                                                                                                                                               
Call Stack (most recent call first):                                                                                                                                                                                                                                                                                                                                                         
  /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1956 (cpack_rpm_generate_package)                                                                                                                                                                                                                                                                
This warning is for project developers.  Use -Wno-dev to suppress it.                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                             
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-server.spec                                                                                                                                                                                                                                                                                       
CPackRPM:Debug: You may consult rpmbuild logs in:                                                                                                                                                                                                                                                                                                                                            
CPackRPM:Debug:    - /irods_build/_CPack_Packages/Linux/RPM/rpmbuildirods-server.err                                                                                                                                                                                                                                                                                                         
CPackRPM:Debug: *** + umask 022                                                                                                                                                                                                                                                                                                                                                              
+ cd /irods_build/_CPack_Packages/Linux/RPM/BUILD                                                                                                                                                                                                                                                                                                                                            
+ mv /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server /irods_build/_CPack_Packages/Linux/RPM/tmpBBroot                                                                                                                                                                                                                                                                              
+ exit 0                                                                                                                                                                                                                                                                                                                                                                                     
+ umask 022                                                                                                                                                                                                                                                                                                                                                                                  
+ cd /irods_build/_CPack_Packages/Linux/RPM/BUILD                                                                                                                                                                                                                                                                                                                                            
+ '[' /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server '!=' / ']'                     
+ rm -rf /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server  
++ dirname /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server                              
+ mkdir -p /irods_build/_CPack_Packages/Linux/RPM/irods                                            
+ mkdir /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server      
+ '[' -e /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server ']'  
+ rm -rf /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server                                             
+ mv /irods_build/_CPack_Packages/Linux/RPM/tmpBBroot /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server
+ /usr/lib/rpm/check-buildroot                                      
+ /usr/lib/rpm/redhat/brp-compress                                                                     
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip                              
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump                                                   
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip                                
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1           
error: Bad exit status from /var/tmp/rpm-tmp.0UDzQX (%install)                                      
    Bad exit status from /var/tmp/rpm-tmp.0UDzQX (%install)              
 ***                                                                                                 
CPackRPM:Debug:    - /irods_build/_CPack_Packages/Linux/RPM/rpmbuildirods-server.out
CPackRPM:Debug: *** Building target platforms: x86_64                                                             
Building for target x86_64                                                             
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.JjjPW4                                  
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.0UDzQX    
Compiling /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server/var/lib/irods/scripts/irods/test/test_all_rules.py ...
  File "/var/lib/irods/scripts/irods/test/test_all_rules.py", line 26
    metaclass = metaclass_unittest_test_case_generator.MetaclassUnittestTestCaseGenerator):
              ^                                                 
SyntaxError: invalid syntax                                                              
                                                              
Compiling /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server/var/lib/irods/scripts/irods/test/test_isysmeta.py ...
  File "/var/lib/irods/scripts/irods/test/test_isysmeta.py", line 18          
    print('I AM A TESTFILE -- [' + self.filename + ']', file=f, end='')                       
                                                            ^      
SyntaxError: invalid syntax                                                                         
                                                                         
                                                                                                 
                                                                      
RPM build errors:                                                                               
 ***                                                                 
CPack: - package: /irods_build/irods-database-plugin-mysql-4.3.0-1.x86_64.rpm generated.            
CPack: - package: /irods_build/irods-database-plugin-oracle-4.3.0-1.x86_64.rpm generated.      
CPack: - package: /irods_build/irods-database-plugin-postgres-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-devel-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-runtime-4.3.0-1.x86_64.rpm generated.                        
+ cp -r /irods_build/irods-database-plugin-mysql-4.3.0-1.x86_64.rpm /irods_build/irods-database-plugin-oracle-4.3.0-1.x86_64.rpm /irods_build/irods-database-plugin-postgres-4.3.0-1.x86_64.rpm /irods_build/irods-devel-4.3.0-1.x86_64.rpm /irods_build/irods-runtime-4.3.0-1.x86_64.rpm /irods_packages/
```

**Comment by SwooshyCueb** [comment]
Figures

**Comment by SwooshyCueb** [comment]
Rebased on top of main.

@korydraughn Mind trying again now that #6347 is merged?

**Comment by korydraughn** [comment]
Sure thing.

**Comment by korydraughn** [comment]
Build failed:
```bash
CPack: Create package using RPM          
CPack: Install projects                         
CPack: - Install project: irods []                                                                              
CPack: -   Install component: irods-database-plugin-mysql
CPack: -   Install component: irods-database-plugin-oracle                              
CPack: -   Install component: irods-database-plugin-postgres            
CPack: -   Install component: irods-dev                                             
CPack: -   Install component: irods-runtime                           
CPack: -   Install component: irods-server                    
CPack: Create package               
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-mysql.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-oracle.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-postgres.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-devel.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-runtime.spec
CMake Warning (dev) at /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1116 (message):
  CPackRPM:Warning: SUGGESTS not supported in provided rpmbuild.  Tag will      
  not be used.                                                                 
Call Stack (most recent call first):                                            
  /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1956 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.          
                                                                               
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-server.spec
CPackRPM:Debug: You may consult rpmbuild logs in:
CPackRPM:Debug:    - /irods_build/_CPack_Packages/Linux/RPM/rpmbuildirods-server.err
CPackRPM:Debug: *** + umask 022                              
+ cd /irods_build/_CPack_Packages/Linux/RPM/BUILD
+ mv /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server /irods_build/_CPack_Packages/Linux/RPM/tmpBBroot
+ exit 0                                                            
+ umask 022                            
+ cd /irods_build/_CPack_Packages/Linux/RPM/BUILD
+ '[' /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server '!=' / ']'
+ rm -rf /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server           
++ dirname /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server      
+ mkdir -p /irods_build/_CPack_Packages/Linux/RPM/irods                        
+ mkdir /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server              
+ '[' -e /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server ']'         
+ rm -rf /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server             
+ mv /irods_build/_CPack_Packages/Linux/RPM/tmpBBroot /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server
+ /usr/lib/rpm/check-buildroot        
+ /usr/lib/rpm/redhat/brp-compress                                             
+ /usr/lib/rpm/redhat/brp-strip /usr/bin/strip                         
+ /usr/lib/rpm/redhat/brp-strip-comment-note /usr/bin/strip /usr/bin/objdump
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1             
error: Bad exit status from /var/tmp/rpm-tmp.kr5XzI (%install)
    Bad exit status from /var/tmp/rpm-tmp.kr5XzI (%install)                                                                  
 ***                                                                                                
CPackRPM:Debug:    - /irods_build/_CPack_Packages/Linux/RPM/rpmbuildirods-server.out
CPackRPM:Debug: *** Building target platforms: x86_64
Building for target x86_64                                    
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.b6MVYx                                       
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.kr5XzI
Compiling /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server/var/lib/irods/scripts/irods/test/test_all_rules.py ...
  File "/var/lib/irods/scripts/irods/test/test_all_rules.py", line 26
    metaclass = metaclass_unittest_test_case_generator.MetaclassUnittestTestCaseGenerator):
              ^
SyntaxError: invalid syntax

Compiling /irods_build/_CPack_Packages/Linux/RPM/irods/irods-server/var/lib/irods/scripts/irods/test/test_isysmeta.py ...
  File "/var/lib/irods/scripts/irods/test/test_isysmeta.py", line 18
    print('I AM A TESTFILE -- [' + self.filename + ']', file=f, end='')
                                                            ^
SyntaxError: invalid syntax



RPM build errors:
 ***
CPack: - package: /irods_build/irods-database-plugin-mysql-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-database-plugin-oracle-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-database-plugin-postgres-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-devel-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-runtime-4.3.0-1.x86_64.rpm generated.
```

**Comment by korydraughn** [comment]
I built the wrong thing.

After pulling the latest changes, things seem better.
```bash
[1001/1002] Run CPack packaging tool...                            
CPack: Create package using RPM                                  
CPack: Install projects                                                        
CPack: - Install project: irods []                                 
CPack: -   Install component: irods-database-plugin-mysql
CPack: -   Install component: irods-database-plugin-oracle      
CPack: -   Install component: irods-database-plugin-postgres                   
CPack: -   Install component: irods-dev                                        
CPack: -   Install component: irods-runtime                                    
CPack: -   Install component: irods-server                                     
CPack: Create package                                                          
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-mysql.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-oracle.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-database-plugin-postgres.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-devel.spec
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-runtime.spec
CMake Warning (dev) at /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1116 (message):
  CPackRPM:Warning: SUGGESTS not supported in provided rpmbuild.  Tag will
  not be used.                      
Call Stack (most recent call first):                               
  /opt/irods-externals/cmake3.21.4-0/share/cmake-3.21/Modules/Internal/CPack/CPackRPM.cmake:1956 (cpack_rpm_generate_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
                                                                       
CPackRPM: Will use GENERATED spec file: /irods_build/_CPack_Packages/Linux/RPM/SPECS/irods-server.spec                       
CPack: - package: /irods_build/irods-database-plugin-mysql-4.3.0-1.x86_64.rpm generated.            
CPack: - package: /irods_build/irods-database-plugin-oracle-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-database-plugin-postgres-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-devel-4.3.0-1.x86_64.rpm generated.
CPack: - package: /irods_build/irods-runtime-4.3.0-1.x86_64.rpm generated.                 
CPack: - package: /irods_build/irods-server-4.3.0-1.x86_64.rpm generated.
+ cp -r /irods_build/irods-database-plugin-mysql-4.3.0-1.x86_64.rpm /irods_build/irods-database-plugin-oracle-4.3.0-1.x86_64.rpm /irods_build/irods-database-plugin-postgres-4.3.0-1.x86_64.rpm /irods_build/irods-devel-4.3.0-1.x86_64.rpm /irods_build/irods-runtime-4.3.0-1.x86_64.rpm /irods_build/irods-server-4.3.0-1.x86_64.rpm /irods_packages/
```
Here are the packages.
```bash
11:12AM kory@kdd-ws:~/dev/development_environment_output/irods_build/cen7 $ ls -l *.rpm
-rw-r--r-- 1 root root   755218 Apr 21 11:19 irods-database-plugin-mysql-4.3.0-1.x86_64.rpm
-rw-r--r-- 1 root root   754631 Apr 21 11:19 irods-database-plugin-oracle-4.3.0-1.x86_64.rpm
-rw-r--r-- 1 root root   757906 Apr 21 11:19 irods-database-plugin-postgres-4.3.0-1.x86_64.rpm
-rw-r--r-- 1 root root  3404862 Apr 21 11:19 irods-devel-4.3.0-1.x86_64.rpm
-rw-r--r-- 1 root root  8981578 Apr 21 11:19 irods-runtime-4.3.0-1.x86_64.rpm
-rw-r--r-- 1 root root 22930795 Apr 21 11:19 irods-server-4.3.0-1.x86_64.rpm
```
These packages worked in the testing environment too. I was able to run three tests and they all passed.

I think we're good.

**Comment by SwooshyCueb** [comment]
Just to confirm, you were able to install them over 4.2.* packages, yeah?

**Comment by korydraughn** [comment]
I didn't try that. I think the testing environment does a first-time install.

I'll look into standing up a CentOS 7 container with 4.2.11.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
