### PR TITLE
[6495] Improve imkdir inheritance performance (4-2-stable)

### PR DESCRIPTION
**Pull request by MartinFlores751**
Improve `imkdir` performance in the case of inheritance by using a subquery in an `UPDATE` statement.
By using a subquery, the planner utilizes an index scan (when optimal) compared to a sequence scan.

The following snippet was produced by creating 10k collections, which has a parent collection with inheritance enabled, before using `EXPLAIN` to estimate the costs of the statements. The first statement is the original, with the second being the new version.

```
ICAT=# EXPLAIN update R_COLL_MAIN set coll_inheritance=12, modify_ts=12 where coll_id=currval('R_ObjectID');
                             QUERY PLAN                              
---------------------------------------------------------------------
 Update on r_coll_main  (cost=0.00..364.79 rows=1 width=713)
   ->  Seq Scan on r_coll_main  (cost=0.00..364.79 rows=1 width=713)
         Filter: (coll_id = currval('r_objectid'::regclass))
(3 rows)

ICAT=# EXPLAIN update R_COLL_MAIN set coll_inheritance=12, modify_ts=12 where coll_id=(SELECT currval('R_ObjectID'));
                                        QUERY PLAN                                        
------------------------------------------------------------------------------------------
 Update on r_coll_main  (cost=0.30..8.31 rows=1 width=713)
   InitPlan 1 (returns $0)
     ->  Result  (cost=0.00..0.01 rows=1 width=8)
   ->  Index Scan using idx_coll_main1 on r_coll_main  (cost=0.29..8.30 rows=1 width=713)
         Index Cond: (coll_id = $0)
(5 rows)
```

### CODE REVIEW

**Comment by trel** [comment]
Amazing.    Well done.

**Comment by trel** [comment]
A 45x speedup for 10k collections.

**Comment by korydraughn** [comment]
I think all that's left is to run it through the test suites?

**Comment by MartinFlores751** [comment]
All tests passed, save for one (irepl) unrelated to this commit/PR.

**Review by alanking — APPROVED** [review]
Seems good to me. I'm not much of an SQL wizard, so let's wait for one more approval before adding #s.

**Review by trel — APPROVED** [review]

**Comment by alanking** [comment]
Alright, let's add the # then

**Pull request merged**
