### PR TITLE
[#5220] cmake: use GNUInstallDirs (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #5220 for this repository.

Will wait for feedback before pushing through Jenkins.

### CODE REVIEW

**Comment by trel** [comment]
i don't see any inconsistencies.  let's go for it - please run through CI.

**Comment by SwooshyCueb** [comment]
Pushing through Jenkins now.

I've made some changes, so you might want to take a second look, particularly in these areas:
- [the last diff chunk of `CMakeLists.txt`](https://github.com/irods/irods/pull/5229/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1604-R1620)
- [`configuration_schemas/update_schema_ids_for_cmake.py:23`](https://github.com/irods/irods/pull/5229/files#diff-0fc463bb7c6494efae11b84c6183df51a3306b1b60c8e9c298e2c763d1873fa3L23)

**Comment by trel** [comment]
process note... hard to see the diff with the force push - consider adding a commit with a note-to-self to 'merge w/ 5220 above'.

what's the [new COMMAND](https://github.com/irods/irods/pull/5229/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR1617) do?

**Comment by SwooshyCueb** [comment]
The new COMMAND just prints out a cmake status message after the schema id has been set, similar to cmake's `Built target [name]` messages. I found it useful to be able to confirm that the python command is being run, and to see where it happens in the build/install process.

**Comment by trel** [comment]
bueno.    i'm happy with this PR if you're happy.   please # when ready.

**Comment by SwooshyCueb** [comment]
Might be a good idea to look at this one more time before I #. I've added another commit implementing the changes we discussed yesterday.

**Comment by trel** [comment]
this feel much better.    if it builds and runs via packaging DEB and RPM, passes tests, and you're happy with non-package-install... please squash to a single commit - and we'll # when clean.

**Comment by SwooshyCueb** [comment]
Hashes added to the whole round of PRs.
It would probably be best to merge them all at once.

**Comment by trel** [comment]
excellent.    will do when green.    thanks.

**Pull request merged**
