### PR TITLE
A couple of small fixes for libstdc++ (main)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses 7211
Addresses 7212

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Changes look good to me.

Please run the unit tests to make sure the server can stand up.

I don't think the core tests need to be run for this PR.

**Comment by SwooshyCueb** [comment]
Unit tests pass

**Review by korydraughn — APPROVED** [review]
Add the pounds when ready.

**Comment by SwooshyCueb** [comment]
\#'d

**Review by alanking — APPROVED** [review]

**Pull request merged**
