### PR TITLE
server-side GenQuery mod for performance

### PR DESCRIPTION
**Pull request by ilarik**
Has patches to build against openssl-1.0.0 in OS X environments, and a patch to server-side GenQuery SQL generator for more performance.

### CODE REVIEW

**Comment by trel** [comment]
Remove the ordering done in `plugins/database/src/general_query.cpp`.

Other changes have already been accounted for.

**Comment by trel** [comment]
We are still ordering the genQuery results in the database in master today...
  https://github.com/irods/irods/blob/master/plugins/database/src/general_query.cpp#L1930-L1932

If we remove the ordering, do we know what other code may assume the results were being sorted?

**Comment by trel** [comment]
This failed tests on master, across multiple OS / database combinations.  Tabling for now.  May revisit later.

```diff
diff --git a/plugins/database/src/general_query.cpp b/plugins/database/src/general_query.cpp                                     
index 50e221a..56a9fdd 100644                                                                                                    
--- a/plugins/database/src/general_query.cpp                                                                                     
+++ b/plugins/database/src/general_query.cpp                                                                                     
@@ -1926,9 +1926,6 @@ generateSQL( genQueryInp_t genQueryInp, char *resultingSQL,                                                
         return USER_STRLEN_TOOLONG;                                        
     }                                                                                             
     setOrderByUser( genQueryInp );                                                                    
-    setOrderBy( genQueryInp, COL_COLL_NAME );                                                                                   
-    setOrderBy( genQueryInp, COL_DATA_NAME );                                                                                   
-    setOrderBy( genQueryInp, COL_DATA_REPL_NUM );                                                                               
     if ( strlen( orderBySQL ) > 10 ) {                                                                                          
         if ( !rstrcat( combinedSQL, orderBySQL, MAX_SQL_SIZE_GQ ) ) { return USER_STRLEN_TOOLONG; }                             
     }                                                                                       
```

**Comment by ilarik** [comment]
We can revisit this later, if you want. I can make a new pull request. Maybe one that doesn't break the tests.

**Comment by trel** [comment]
Of course, whatever makes sense.

The sorting of the output can't be changed without a deeper dive into the other assumptions in the server and data structures getting these genquery results.

**Pull request closed without merging**
