### PR TITLE
[#6214,#7435] A couple of small cmake tweaks (4-3-stable)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses #6214
Addresses #7435

Ignore the branch name

### CODE REVIEW

**Comment by korydraughn** [comment]
Let's replace the FIXME with a TODO since the plan is to eventually improve it.

Open issues for the TODOs and attach the issue number to the TODO comments.

Other than that, the changes look fine.

**Review by korydraughn — APPROVED** [review]
Looks ready to me. Pound it.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
