### PR TITLE
[_6740] tests for iqstat (4-3-stable)

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Add the pound if the core tests pass for this PR or for #6941.

**Comment by alanking** [comment]
We will need to add the new test to the test list here as well. See https://github.com/irods/irods/pull/6941#pullrequestreview-1317718866

**Review by alanking — COMMENTED** [review]
Looks good. Please also cherry-pick https://github.com/irods/irods/pull/6941/commits/1d884af1f2a2d5f4a37025ccce287a40c63ee6a2 from #6941

Linking https://github.com/irods/irods_client_icommands/pull/367 for future-self...

**Comment by d-w-moore** [comment]
And, need to add # to the prev. commit.

**Review by alanking — APPROVED** [review]
Good. Please add other #

**Comment by d-w-moore** [comment]
ok other # added

**Pull request merged**
