### PR TITLE
[#7626] ModDataObjMeta: Fix ADMIN_KW usage with ALL_KW (main)

### PR DESCRIPTION
**Pull request by alanking**
Addresses #7626

Unit tests pass. Need to run the core tests.

### CODE REVIEW

**Comment by alanking** [comment]
Core tests passed for commit https://github.com/irods/irods/pull/7632/commits/e9ec9473b8190f53a4223079539df1722a38d8de. All the other changes have been to the unit test, which still passes.

**Comment by alanking** [comment]
Squashed

**Review by korydraughn — APPROVED** [review]
Consider squashing to one commit.

Up to you.

**Comment by alanking** [comment]
I prefer to keep my test separate where possible for easy validation. Happy to squash to one next time if we decide to make that part of the process. For now... mergin.

**Pull request merged**
