### PR TITLE
Refactor/Improve iphymv + new rules/tests for irepl + move finalize logic to APIs (master)

### PR DESCRIPTION
**Pull request by alanking**
Giving another look at this as there are some other things I'd like to do.

CI tests passed

### CODE REVIEW

**Comment by trel** [comment]
I think you can squash the codacy items into their 'home' commit - and then we'll eyeball one more time and add all the #s.


> +5,608 −2,006

whew.

**Comment by alanking** [comment]
Tests passed

**Comment by trel** [comment]
please add the glorious #s

**Comment by alanking** [comment]
#'d

**Pull request merged**
