### PR TITLE
[#7570] Add GenQuery2 API (4-3-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cherry-pick of #7582.

Please review the CMake for anything that's specific to the main branch.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good to me. Let's wait for @SwooshyCueb to eyeball the CMake.

**Review by SwooshyCueb — APPROVED** [review]
LGTM

**Comment by korydraughn** [comment]
#'d

**Comment by korydraughn** [comment]
Wait, are the github actions correct?

**Comment by korydraughn** [comment]
Ignore that last comment. Was looking at the wrong thing.

**Pull request merged**
