### PR TITLE
Slow rebalance with iRODS 4.2.4 and PostgreSQL 11.1

### PR DESCRIPTION
**Pull request by jthiltges**
The following query has been running for over 15 days on a system with ~8M records and two replicas.

```select distinct data_id from R_DATA_MAIN where data_id in (select data_id from R_DATA_MAIN where resc_id in (10016)) and data_id not in (select data_id from R_DATA_MAIN where resc_id in (10014)) and modify_ts <= '01571939628' limit 500```

Rewriting the query to use `EXCEPT` for the set math seems much faster, returning results in about 70 seconds. The change is implemented in this PR.

This PR is submitted as draft, as I have not tested iRODS with this change. I'd appreciate a review from someone who understands the spirit of the query.

### CODE REVIEW

**Comment by trel** [comment]
This is great - will look a bit closer in the next few days.

Also note... MySQL doesn't implement `EXCEPT` - but can use a `LEFT JOIN` to simulate the `MINUS`/`EXCEPT` notation.

http://www.mysqltutorial.org/mysql-minus/

**Comment by jthiltges** [comment]
Reopening to retry travis-ci build

**Comment by alanking** [comment]
I have run core tests on this change and all tests passed as expected.

**Comment by anderbubble** [comment]
@trel what is standing in the way of this getting merged? Can it be in the next release?

**Comment by trel** [comment]
Yes, we can get it included if it passes all three database suites in CI.

Please squash these three commits down to one and update the commit message to begin with our bracketed notation [#xxxx] to link with issue 4731.

**Comment by jthiltges** [comment]
Commits are squashed and rebased against master. Thank you for taking a look at it.

**Comment by trel** [comment]
running through CI again, will remove draft status, and get it merged - thanks!

**Pull request merged**
