### PR TITLE
[#5776] API plugins are now part of the irods-runtime package (master)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by korydraughn** [comment]
@SwooshyCueb Do you see any potential issues with this change for master and 4-2-stable?

**Comment by SwooshyCueb** [comment]
I do not think we should make this kind of change for stable, but I don't see any problem with doing it for master

**Review by SwooshyCueb — APPROVED** [review]

**Comment by korydraughn** [comment]
Ok. Can you explain why you feel this is not appropriate for 4-2-stable? Do you expect this could negatively affect deployments or is it something else?

**Comment by SwooshyCueb** [comment]
It's not *as big of a deal* now since we're not doing debian packaging properly (debian packages track symbols and complain loudly when any disappear unexpectedly), but it's still generally considered bad practice to change which package in which a binary resides in a minor update, particularly one so late in the lifecycle of the major update series.
To answer your question more directly, yes I think it *could* negatively affect deployments, but I don't know offhand if it *would*. I can't point to any specific issues I know would crop up if we make this change in stable, but it's not something I feel comfortable giving my stamp of approval.
That said, I don't feel super strongly about it, but if you think you have a really good reason for doing it in stable, feel free to disregard my opinion.

**Comment by korydraughn** [comment]
That makes sense. We'll let @trel see your comment and then we can make a decision about whether we want to make this change for 4-2-stable.

**Comment by trel** [comment]
We're not removing a symbol as much as moving it.

Since `irods-runtime` is always installed - this doesn't prevent anyone's future work/compatibility.    And it adds the functionality we need for `itouch`...

I think this is a safe and correct approach fr 4-2-stable.

**Comment by korydraughn** [comment]
Added #

**Pull request merged**
