### PR TITLE
[#6754] Deprecated member variables of the l1desc data type (main)

### PR DESCRIPTION
**Pull request by korydraughn**
Ported from #6793.

Will run unit tests and core tests soon.

### CODE REVIEW

**Comment by korydraughn** [comment]
Unit tests passed.

Running core tests.

**Comment by korydraughn** [comment]
All core tests passed.

Adding #

**Comment by korydraughn** [comment]
#'d

**Comment by korydraughn** [comment]
Let me fix the clang-format/tidy before merging this.

**Comment by korydraughn** [comment]
Ready to be merged.

**Review by alanking — APPROVED** [review]

**Pull request merged**
